wiris/html-integrations

packages/mathtype-html-integration-devkit/src/popupmessage.js

This error is solved in the devkit package. 
The error was reproducable with
1. Click MathType toolbar icon
2. Make MathType window full-screen
3. Type something
4. Click twice outside the modal window
5. Get the error: Uncaught ReferenceError: _wrs_modalWindow is not defined    at Yb.show (popupmessage.js:120)    at Kb.showPopUpMessage (modal.js:1407)    at Kb.cancelAction (modal.js:285)
This pull requests solves this error, it stops appearing and the modal window works as expected.
You'll have to test if the error does not appear any more in any browser or editor (since the error was in the devkit package) and that the modal window does not do anything weird and works as expected

KB-5030:  Clicking outside MathType modal window results in error

---

demos/html5/ckeditor5/package.json
packages/mathtype-ckeditor5/src/integration.js

See original issue: https://github.com/wiris/html-integrations/issues/94
## Description
The code for this pull request solves a problem with the wiris modal in the ckeditor5: appears an error when deleting a formula on the editor that is being edited in the wiris modal.
In order to accept this review you must check that the code is reliable, that it follows good practices, that it solves the problem mentioned, and that it does not break other aspects of the plugin.

[CKEditor 5] Removing MathType equation which is being edited results in a crash

---

README.md
demos/README.md
demos/angular/ckeditor5/README.md
demos/angular/froala3/README.md
demos/html5/ckeditor4/webpack.config.js
demos/html5/ckeditor5/webpack.config.js
demos/html5/froala2/webpack.config.js
demos/html5/froala3/webpack.config.js
demos/html5/generic/webpack.config.js
demos/html5/tinymce4/webpack.config.js
demos/html5/tinymce5/webpack.config.js
packages/mathtype-html-integration-devkit/src/contentmanager.js
packages/mathtype-html-integration-devkit/src/modal.js

An error stops execution when opening MathType with some
iOs simulated user agent. The error differs depending on the browser.
On real iOS devices everything works as expected and there are no errors
on the console, though.
The bug is fixed by making sure the 'modalDialogInstance' is available on
execution time.
Fixed by improving the browse detection method for iOs devices
on the contentmanager class.
- Update demos: Set the right editor name on the title's section
- Update README: Refrain some instructions for better understanding
- Make devserver accessible on all html5 demos
> In order to test this on actual mobile devices, one must expose the
> demos to the local network. To do this, just modify the
> webpack.config.js file for the desired demo so as to include
> host: '0.0.0.0'  in …

Kb 2259: Fix multiple issues on the MathType editor on iOS devices

---

packages/mathtype-ckeditor5/src/plugin.js

This pull request fixes issue #96, which stops the user from inserting a new line after a MathType formula in CKEditor 5.
1. Add MathType equation as last element in the editor
2. Try to navigate to the end of the equation and press `enter`
Expected: a new line is inserted.
Actual: no new line is inserted, and the caret disappears.
For more details see #96.

[CKEditor 5] Not able to insert new line after MathType equation in Firefox

---

demos/html5/ckeditor4/package-lock.json
packages/mathtype-ckeditor4/plugin.src.js

This pull request fixes issue #115, which calls the event onChange bero aplying the mathtype formula changes on CKEditor4
1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html
2. Handle 'change' event of editor, paste in dev console:
3. CKEDITOR.instances.editor1.on( 'change', function() { console.log( 'change event data', this.getData() ); } );
4. Delete all content in ckeditor
5. Launch mathtype from the editor
6. Add math formula and click insert
7. Editor 'change event is fired, when you click insert button on mathtype.
8. call editor.getData(), returns empty result
9. Formula is is inserted into ckeditor.
10. Solved changing the order when calling on change event.
Expected: when call step 7 above, expected to get the mathml code as data.
Actual: returns empty.
For …

[CKEditor 4] onChange event is getting called before aplying mathtype changes

---

demos/angular/ckeditor5/package.json
demos/angular/ckeditor5/src/app/app.component.ts
demos/angular/ckeditor5/src/index.html
demos/angular/froala3/package.json
demos/angular/generic/package.json
demos/angular/tinymce5/package.json
demos/html5/ckeditor4/index.html
demos/html5/ckeditor4/package.json
demos/html5/ckeditor4/src/app.js
demos/html5/ckeditor5/package.json
demos/react/ckeditor5/package.json

This pull request adds some changes to make the CKEeditor demos 
always use the latest version of the MathType SDK package.
This last version solves the issue https://github.com/wiris/html-integrations/issues/38.
With these changes, we'll can answer the reporter of the issue with step-by-step
instructions to validate the solution for himself by testing any of the CKEditor
demos included on this repository.
Also, some minor changes have been added, too:
- Use branded name for CKEditor.
- Update 'author' field to the whole team on most demos.
- Make the CKEditor demo accesible through the net.
- Make angular demos accesible through the net.
- Update dependencies on some demos.
- Update React demos to use latest SDK version.
- Make React/CKEditor demo through the net.

Update CKEditor demos to the most recent SDK version

---

packages/mathtype-ckeditor4/package-lock.json
packages/mathtype-ckeditor4/plugin.src.js

This pull request fixes issue #114, which when having the source button with mathtype, it breaks the second time the button is cliked.
1. open https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html
2. click on source button, to show code view
3. click on source again, to show WYSIWYG view.
4. click on source button, to show code view
5. click on source again, to show WYSIWYG view.
Expected: show WYSIWYG view and able to launch mathtype.
Actual: script error.
For more details see #114 .
The problem was solved in the mathtype from CKEditor 4 plugin,
that this did not take into account the source feature.

[CKEditor4] click on source the second time breaks mathtype

---

demos/html5/ckeditor4/package-lock.json
demos/html5/ckeditor4/src/app.js
demos/html5/ckeditor5/package-lock.json
demos/html5/ckeditor5/package.json
demos/html5/ckeditor5/src/app.js
demos/html5/ckeditor5/test/e2e-language-languageobjectstring.test.js
demos/html5/froala2/src/app.js
demos/html5/froala3/src/app.js
demos/html5/generic/src/app.js
demos/html5/tinymce4/src/app.js
demos/html5/tinymce5/src/app.js
lerna.json
packages/mathtype-ckeditor4/plugin.src.js
packages/mathtype-ckeditor5/babel.config.js
packages/mathtype-ckeditor5/jest.config.js
packages/mathtype-ckeditor5/package-lock.json
packages/mathtype-ckeditor5/package.json
packages/mathtype-ckeditor5/src/integration.js
packages/mathtype-ckeditor5/src/plugin.js
packages/mathtype-froala/wiris.src.js
packages/mathtype-froala3/wiris.src.js
packages/mathtype-generic/wirisplugin-generic.src.js
packages/mathtype-html-integration-devkit/jest.config.js
packages/mathtype-tinymce/editor_plugin.src.js

Language property was not accepted through MathType parameters in mathtype plugins.
This pull request changes the definition of the language on the mathtype with the following priorities:
1. Sets the value of the language if this property is defined in MathtypeParameters.
2. Sets the value of the language if the editor language is defined.
3. If none of the above, gets the browser language.
The points mentioned above are those that should be checked if they work as expected. The demos are prepared to reproduce the behavior and the steps are the following:
1. Choose a demo.
2. In the app.js file, there is code to define the language both behind MathtypeParameters and the way the editor defines a language.
3. Comment out and uncomment the mentioned lines to test that the language works …

Set Mathtype to accept language property though MathType parameters

---

packages/mathtype-html-integration-devkit/README.md
packages/mathtype-html-integration-devkit/package.json
packages/mathtype-html-integration-devkit/src/core.src.js
packages/mathtype-html-integration-devkit/src/test.js

The third argument in `getService` must be a Boolean value and must be `true` to send a GET request:
https://github.com/wiris/html-integrations/blob/fa065dabaf3487b13ee00d67d4364c316b19dcb7/packages/mathtype-html-integration-devkit/src/serviceprovider.js#L200-L217
- Original author: @ilyasgaraev
- Pull request originak and closes #147

KB-10021: Use GET request for configurationjs

---

packages/mathtype-html-integration-devkit/src/util.js
packages/mathtype-tinymce4/package.json
packages/mathtype-tinymce5/package.json

This pull request fixes KB-10221, which states that formulas can be resized to be bigger in TinyMCE 4 and 5.
When resizing a formula in TinyMCE, if the mouse is dragged outside of the text editor, and the mouse button released, then the formula stays resized until the editor is clicked again. This does NOT affect the output of the editor, i.e. if we click "Update" in one of the demos, the rendered formula presents the correct sized. This is just a visual bug.
The bug is caused by the fact that some browsers (Chrome and Safari for instance) do not trigger the mouseup event for the HTML element of the TinyMCE editor if the mouse is *not* on the editor when the mouse button is released. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseup_event), this is the …

KB-10221: Formulas can be resized in TinyMCE 4 and 5

---

packages/mathtype-ckeditor4/package.json
packages/mathtype-ckeditor5/package.json
packages/mathtype-froala/package.json
packages/mathtype-froala3/package.json
packages/mathtype-generic/package.json

This pull request fixes KB-10335, which states that there's a missing carret in the html-integration-devkit dependency on the mathtype plugins to let lerna work the expected way.
In all the packages of the plugins of mathtype, there's a dependency, html-integration-devkit that sould have a caret (^) in the beggining. This missing caret makes the lerna arquitecture not working when trying to link the dependency to the local package.
Add the missing carret on the html-integration-devkit dependency on all the mathtype plugins (except tinymce4 and 5, it is in another PR)

Add carret to html-integration-devkit plugins dependency

---

packages/mathtype-froala/wiris.src.js
packages/mathtype-froala3/wiris.src.js
packages/mathtype-generic/wirisplugin-generic.src.js
packages/mathtype-html-integration-devkit/src/integrationmodel.js
packages/mathtype-html-integration-devkit/src/modal.js

This pull request fixes KB-10222, which states that there's a loss of information when changing from MT to CT and from CT to MT when editing an existing formula in Froala2 and 3, and Generic editors.
A user opens an existing formula to start editing it and changes the editor from MT to CT, this action generates the loss of the formula the user was working on in the editor
This is because the froala editor and the generic editor does not keep the existing formula to edit selected while we are in the MT or CT editor.
The proposed solution, included in this PR, consist in assign to a temporal register on the current instance, the image of the existing formula that is going to be opened to be edited. Then, every time a new formula is going to be opened, it has to be checked if exists or not …

Changing from MT to CT while editing a formula causes a loss of information

---

packages/mathtype-ckeditor5/src/plugin.js

This pull request fixes KB-10332, which states that there's a sintax mistake with the currentInstance component in the CKEditor5.
Although the current instance component is not really used in the CKEditor5 plugin, it exists and sould be consistent with the current instances of the other wiris plugins. In this case there's a sintax error: it actually is "CurrentInstance" when it  should be "currentInstance".
Change the syntax error in all the places where the bad currentInstance of the CKEditor5 plugin appears.
This fix should not break anything, but just to be cautious you can check that the CK5 demo works propertly with the change

Solve the sintax error with the currentInstance CKEditor5

---

README.md
demos/README.md
demos/html5/ckeditor5/package.json
scripts/installCK5windows.js

Solved by adding a script in the package.json CK5 file
that can be executed in all the SO but it's slower than
the regular one.
Issue reproducable just in the CKEditor5 + html5 demo with the npm run build-dev command.
Now, on windows, instead of using npm run build-dev, it has to be used npm run build-dev-windows.
It has to be tested that this command works as expected and that the script created for that is correct.
Issue found by QA team.

Solve CK5+windows+build-dev issue

---

demos/html5/generic/src/app.js
packages/mathtype-generic/wirisplugin-generic.src.js

This pull request fixes KB-10710, which states that the latex formulas introduced as $$formula$$ are not rendered when clicking the update button in the Generic integration.
A user creates a formula using latex in the Generic editor, clicks the update button and it should be rendered as a mathml formula, but it stays as a plain text with the latex structure.
This happens because latex formulas can not automatically be rendered. They need a intermedium process to render them as a mathml formula.
The proposed solution, included in this PR, consist in create a get function in the generic plugin that gets the inner html of the editable block area, parses it with a intermedium procces that renders the latex formulas, and returns it. This get function will be used in the update process.

Solve Latex rendering issues

---

packages/mathtype-froala3/wiris.src.js

This PR solves bug KB-9825.
Formulas shouldn't be able to be edited in Froala 3 readonly mode.
1. Use Froala is in readonly mode, with some predefined text that contains a formula.
Formulas cannot be edited.
By double-clicking the formulas, they can still be edited.
To test this, you can enable readonly mode in the demos by adding in `demos/html5/froala3/src/app.js` the following line:
```js
this.edit.off()
```
Inside the `initialized` method.

Don't allow editing formulas in Froala 3 readonly mode

---

packages/mathtype-html-integration-devkit/README.md
packages/mathtype-html-integration-devkit/package-lock.json
packages/mathtype-html-integration-devkit/package.json

In order to generate the jsdoc documentation a new npm command has been added to the project: "npm run build-docs".
Also, the git@github.com:wiris/mathtype-integration-jsdoc-theme project needs to be downloaded.
> This previous step has been included on the npm command, too.
Therefore these are the instructions to generate the jsdoc folder from scratch:
1. Clone the html-integrations project
```bash
git clone git@github.com:wiris/html-integrations.git
cd html-integrations
```
2. Install `mathtype-html-integration-devkit` dependencies.
```bash
npm install
```
3. Compile the documentation using `jsdoc` command:
```bash
npm run build-docs
```
**Note:** This last step clones the jsdoc-theme on the `mathtype-html-integration-devkit` package, automatically.
The js-doc theme needs to be cloned …

KB-11273: Add a jsdoc generation command

---

.eslintrc.js
docs/development/linting/README.md
resources/demos/angular-imports.js
resources/demos/imports.js
resources/demos/react-imports.js

The 'import' clausules were not included on our linting strategy.
This was causing that there were still a lot of uncontrolled Javascript errors in our codebase with exports and imports statements.
- The js linting configuration file has been updated to include the 'import' eslint module configuration.
- The export sentences on the common resources used by React and Angular demos have been commented.
- The import statements have been changed from 'error' to 'warn' to avoid stopping the build procedure.
#taskid: 11600

KB-11600: Add 'import' support to linting strategy

---

packages/mathtype-ckeditor4/package.json
packages/mathtype-ckeditor5/package.json
packages/mathtype-froala/package.json
packages/mathtype-froala3/package.json
packages/mathtype-generic/package.json
packages/mathtype-tinymce4/package.json
packages/mathtype-tinymce5/package.json

`"@wiris/mathtype-html-integration-devkit": "^1.5.1"
`
The MathType published packages are not properly linked
to GitHub so it's not possible to manage the
third-party dependency graph.
Adding the 'repository' key on all editor packages should
fix this.
Also on this commit:
- Remove unused 'esdoc' settings on generic.
- Set https on homepage setting.

Add the 'repository' key on all editor packages and set dev-kit dependency version

---

.eslintignore
packages/mathtype-html-integration-devkit/src/integrationmodel.js
packages/mathtype-html-integration-devkit/src/modal.js

Focus is not coming back to any editor when user does not type anything in the MathType editor and clicks cancel button.
Open any demo
Insert or modify a formula
Click on cancel button or escape
The focus is lost
The solution added on this PR uses the same logic applied on the insert button to gt back the focus.
It is added in a function that gets called every time the modal is closed by a cancel action on every editor.
---
Closes #133
[#taskid 6837](https://wiris.kanbanize.com/ctrl_board/2/cards/6837/details/)

Focus is not coming back to TinyMCE when Cancel button is pressed on MathType editor

---

demos/html5/froala/package-lock.json
package-lock.json
packages/mathtype-froala/wiris.src.js
packages/mathtype-froala3/wiris.src.js

This PR adds a solution to an issue that appears whenever a user clicks Wiris icons in Froala toolbar, or double clicks in any part of the editor. The error is a console one, but doesn't seem to break anything, and has different messages between browsers:
* **Safari**: TypeError: Can only call Element.closest on instances of Element
* **Firefox**: Uncaught TypeError: 'closest' called on an object that does not implement interface Element. 
* **Chrome**: Uncaught TypeError: Illegal invocation
In order to reproduce the bug you should:
1. Start the Froala demo
2. Click Wiris button in Froala toolbar, or double click on a formula or the editor itself
3. Observe error in console;
4. Optionally debug contentChanged hook is triggered.
In order to check that the bug has been solved you should …

[MathType] [Froala] Uncaught TypeError: Illegal invocation

---

packages/mathtype-ckeditor5/src/plugin.js

Hi, I'm a core developer of CKEditor 5 👋
Just wanted to let you know that in CKEditor 5 we're working on the unsafe attribute filtering in the editing layer. Currently, this feature is disabled ([behind a flag](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_domconverter-DomConverter.html#member-experimentalRenderingMode)) but in the nearest future, it will be enabled by default.
We noticed that in order to comply with the new filtering mechanism, the MathType plugin has to allow the `src` attribute in the editing layer (considered unsafe because it contains `data:image/svg+xml...`).
Would you consider merging this change so your integration will smoothly align to the upcoming CKEditor 5 API?
Please let me know if something is unclear.  
Thanks!

Allowed unsafe "src" attribute on the <img> element to override CKEditor 5 filtering mechanism

---

CHANGES.md
packages/mathtype-ckeditor4/README.md
packages/mathtype-ckeditor5/README.md
packages/mathtype-froala/README.md
packages/mathtype-froala3/README.md
packages/mathtype-generic/README.md
packages/mathtype-tinymce4/README.md
packages/mathtype-tinymce5/README.md

wiris.net services access has changed and is not allowed to use a service without www in the hostname. Added missing 'www' on documentation wiris.net links.
---
[#taskid 34](https://wiris.kanbanize.com/ctrl_board/2/cards/34/details/)

Added missing 'www' on documentation wiris.net links

---

CHANGES.md
packages/mathtype-ckeditor5/src/plugin.js
packages/mathtype-html-integration-devkit/src/integrationmodel.js
packages/mathtype-html-integration-devkit/src/util.js

Implemented the inherited `destroy?(): void` function on `plugin.js` file from `packages/mathtype-ckeditor5`, in order to remove all event listeners from the CKEditor5Integration object when CKEditor5 is destroyed. Remove the event listeners allow the garbatge collector free up the memory of the CKEditor5Integrations object.
1. Close all Chrome windows.
2. Run html5 CKEditor5 demo with a guest profile.
3. Initialize the editor, then destroy it a couple of times. Click the Garbage Collector button after each destruction. Make sure no references are left behind (such as window.editor).
4. Take a memory snapshot.
5. Repeat 3.-4. a couple of times.
There should be no dramatic difference in snapshot size and retained memory.
---
Closes #459 
[#taskid …

Destroy events from CKEditor5Integration when CK5 is destroyed

---

CHANGES.md
demos/angular/generic/src/app/app.component.ts
demos/html5/generic/src/app.js
demos/react/generic/src/index.js
packages/mathtype-generic/global.js
packages/mathtype-generic/wirisplugin-generic.src.js

This PR solves a bug with the Parser functions and the Generic Integration. The bug turned off the Parser functions, so they returned the exact same parameter they received, instead of transforming it. For example, executing the following function:
```js
WirisPlugin.Parser.initParse('<math><mo>x</mo></math>');
```
should return the mathml transformed into an image, but instead returns the same mathml.
This behavior is caused due to a bad configuration variable on the `global.js` mathtype-generic package file, and a wrong way to initialize the generic editor instance on the HTML5, Angular and React demos.
1. Open the Generic demo.
2. With F12, open the web inspector.
3. On the console tab, write the following code: `WirisPlugin.Parser.initParse('<math><mo>x</mo></math>');`
4. See that the …

Solve parser functions not working on Generic Integrations

---

CHANGES.md
packages/mathtype-html-integration-devkit/src/mathml.js

When adding latex to our MathML formulas, we include a semantics field that can make formulas render badly when the wiris plugins are not used to render them, for example, not including the plugin and trying to render the formulas with firefox browser.
This is caused due to a specification of the `semantics` field. It requires to have all the MathML associated to the Latex formula inside a `mrow` tag.
1. Add the following mathml to the source code:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
<semantics>
<mfrac>
<mrow>
<mn>8</mn>
<mo>&#xB7;</mo>
<mn>4</mn>
</mrow>
<mn>12</mn>
</mfrac>
<mo>+</mo>
<mfrac>
<mrow>
<mn>1</mn>
<mo>&#xB7;</mo>
<mn>3</mn>
</mrow>
<mn>12</mn>
</mfrac>
<mo>=</mo>
<mfrac>
<mrow>
<mn>32</mn>
<mo>+</mo>
<mn>1</mn>
</mrow>
<mn>12</mn>
</mfrac>
<mo>=</mo> …
```

Fix wrapping issue when converting Latex to MathML

---

CHANGES.md
demos/angular/froala/package.json
demos/html5/froala/index.html
demos/html5/froala/package.json
packages/mathtype-froala3/package.json
packages/mathtype-froala3/webpack.config.js
packages/mathtype-froala3/wiris.src.js

The Wiris formulas images should have a different behavior than regular images when clicking into them, meaning that the image toolbar for formulas should include the mathtype buttons when specified. With angular framework and Froala v3 or v4 editor, this behavior was not working, instead, the formulas were treated as regular images even when the image toolbar had specified the mathtype buttons.
The bug was solved by:
- Deleting jQuery residual code on mathtype-froala3 package, since Froala3 and above works with pure JavaScript.
- Migrating webpack v4 to v5.
This PR also includes:
- Removing jQuery dependency from html5+froala demo.
- Updating Froala version on angular and html5 + froala demos.
1. Open the angular + froala demo.
2. Click on any formula on the editor.
3. Check that the …

Fix Froala v3 & v4 + Angular treating formulas as images

---

CHANGES.md
docs/adr/005-Use-HTML-sanitizer-to-avoid-XSS-attacks.md
packages/mathtype-html-integration-devkit/README.md
packages/mathtype-html-integration-devkit/package.json
packages/mathtype-html-integration-devkit/src/parser.js

Detected an XSS vulnerability on the Mathtype devkit package. A user could inject malicious to a website code encaplusating them inside a <math> tag.
In order to prevent XSS attacks it is proposed to use the DOMPurify library. An open-source XSS sanitizer for HTML, MathML and SVG.
DOMPurify sanitize HTML and prevents XSS attacks. You can feed DOMPurify with string full of dirty HTML and it will return a string removing the dangerous HTML.
DOMPurify will be added to @wiris/mathtype-html-integration-devkit so this dependency will affect to all the html-integrations packages.
---
[#taskid 17724](https://wiris.kanbanize.com/ctrl_board/2/cards/17724/details/)

KB-17724: Add an ADR document for XSS vulnerability when browser engines parsing HTML

---

README.md
demos/angular/ckeditor5/README.md
demos/angular/froala/README.md
demos/angular/generic/README.md
demos/angular/tinymce5/README.md
demos/react/froala/README.md
docs/contributing/README.md

On our last Engineering teams lead meeting, we decided to adopt the Conventional Commits specification to commit messages to all our source code projects.
Therefore, we need to update our Contributing guidelines section to adhere to this new standard and allow others to do, so.
The main benefits of this initiative are:
- Provide better information when browsing the history.
- Allow generating `CHANGELOG` by script.
- Allow ignoring commits by `git bisect`.
- Automatically determining a semantic version bump (based on the types of commits landed).
- Communicating the nature of changes to teammates, the public, and other stakeholders.
- Be able to trigger build and publish processes.
- Make it easier for people to contribute to your projects, by allowing them to explore a more structured …

docs: add support for conventional commits (KB-18015)

---

.github/workflows/publish.yml
.gitignore
.vscode/extensions.json
docs/adr/005-use-verdaccio-for-emulating-publishing-npm-packages.md
docs/adr/006-use-expect-for-automating-tui-interaction.md
docs/adr/007-use-verdaccio-for-emulating-publishing-npm-packages.md
resources/publish/.npmrc
resources/publish/config.yaml
resources/publish/htpasswd
scripts/publish.exp

This PR adds a new GitHub Actions workflow capable of automatically publishing the front-end npm packages.
It has two main additions:
- ADRs, justifying the technical decisions taken. Please read those and comment if there is any disagreements.
- Code changes, including:
- A new workflow (`.github/workflows/publish.yml`).
- A new Expect script (`scripts/publish.exp`) in charge of managing Lerna, used by the previous workflow.
---
[#taskid 17161](https://wiris.kanbanize.com/ctrl_board/2/cards/17161/details/)

[KB-17161] Automated release for npm packages

---

CHANGES.md
packages/mathtype-generic/README.md
packages/mathtype-generic/getting_started.md
packages/mathtype-generic/services.md
packages/mathtype-html-integration-devkit/doc/src/getting_started.md
packages/mathtype-html-integration-devkit/doc/src/services_generic.md

The NPM generic MathType package documentation, on how to integrate MathType, is missing  the following step:
```js
WirisPlugin.currentInstance = this.wiris_generic;
```
This leads to errors when interacting with the close buttons on the MathType modal.
The files where the documentation was missing a step had been updated:
* `mathtype-generic` markdown files
* `mathtype-html-integration-devkit` markdown files
Updated the CHANGELOG.md
* Follow the instructions on the [NPM mathtype-generic](https://www.npmjs.com/package/@wiris/mathtype-generic) page to integrate MathType on your application.
* When trying to close the MathType modal, a console error will appear and the modal will not close.
---
We realised there was a missing step thanks to the, already closed, #330 issue
[#taskid …

NPM MathType Generic integration instructions lead to errors with close buttons

---

CHANGES.md
demos/html5/ckeditor5/package.json
packages/mathtype-ckeditor5/src/integration.js
packages/mathtype-ckeditor5/src/plugin.js

The mathtype integration with CKEditor5, made both from CKEditor builder or npm dependencies, does not update the tooltip language. The editor and mathtype modal are both in the specified language while the toolbar Wiris buttons are shown in English. 
This issue was because the label on the Wiris toolbar buttons was static, so when the editor had a different language defined than english, the buttons were still in english.
This PR solves this issue by making the label button property dynamic instead of static.
> **Note**: this PR has been recovered from a reverted state at the KB-13890 branch.
1. Clone the repo
2. Edit lerna.json to compile the `demos/html5/ckeditor5` demo
3. Run `npm install`
4. Run `npm start`
2. Edit the demo and define a language following the CKEditor5 guidelines
* …

KB-13890: CKEditor5 integration language changes the toolbar buttons language except the wiris ones

---

packages/mathtype-froala3/webpack.config.js

The BUGSPRINT branch contains adds a new bug when updating the mathtype-froala3 package webpack to v5. The top right MathType buttons are functional but not visible. See the image below for clarification.
On webpack v4, the icons are loaded through raw-loader with the following pre-fix: `!!raw-loader!`, which is not supported on v5.
Downgrade mathtype-froala3 to **webpack** v4 and destinate a single task to upgrade all the webpack versions.
1. Copy the content from the lerna.demos.json to the lerna.json file.
2. Run the follwing commands on the root project:
```shell
npm install
npm run start
```
3. Go to the **demos/html5/froala** folder
4. Run `npm run` start
5. Open the MathType modal.
---
[#taskid 21424](https://wiris.kanbanize.com/ctrl_board/2/cards/21424/details/)

fix(froala3): Solve top right buttons not showing

---

CHANGES.md
packages/mathtype-tinymce/editor_plugin.src.js

The redo & undo buttons were broken when interacting
with the MathType formulas
This PR fixes the following issue: If the user inserts a formula in TinyMCE4 or TinyMCE5 and then presses the Undo button followed by the Redo button, the formula that should be recovered, will be lost.
This has been solved by adding the edited and created formulas on a TinyMCE queue that stores the changes made by the Undo and Redo buttons
* Updated the Changes.md
1. Open TinyMCE4 or TinyMCE5 demo.
2. Create and Insert a formula using MT or CT.
3. Click the Undo button. The formula disappears.
4. Click the Redo button.
---
Closes #275 
[#taskid 14441](https://wiris.kanbanize.com/ctrl_board/2/cards/14441/details/)

fix(tinymce): Redo & undo buttons broken

---

CHANGES.md
packages/mathtype-html-integration-devkit/src/popupmessage.js

This PR fix the issue: when user opens the MathType Editor and starts writing a formula and cancels the process by clicking on Cancel, the HTML Editor is not focused, i.e., the user doesn't see the caret is placed where it was before opening MathType.
Now the function `setActionsOnCancelButtons()` is called after `cancelCallback()`.
* Updated the Changes.md
1. Open the demo
2. Click on the MT icon
3. Type anything inside the MT Editor
4. Click on the Cancel button (it triggers the "Are you sure you want to leave?" dialog)
5. Click on the Close button
---
[#taskid 21616](https://wiris.kanbanize.com/ctrl_board/2/cards/21616/details/)

fix: focus when cancel insertion mt editor

---

packages/mathtype-ckeditor5/src/integration.js

When opening the CK Editor 5 demo and directly inserting a formula in the HTML Editor by clicking the MT/CT icon, the caret is placed before the fomula.
1. Open the CK Editor 5 demo
2. Click on the MT icon on the HTML Editor (it opens the MT modal window)
3. Insert any equation on the MT modal window and click on Insert (the formula is inserted in the HTML Editor)
---
[#taskid 21516](https://wiris.kanbanize.com/ctrl_board/2/cards/21516/details/)

fix: caret after the formula on first insertion

---

CHANGES.md
packages/mathtype-html-integration-devkit/src/contentmanager.js

When the user opens the MT/CT Editor using an iOS device with zoomed webpage. The user will not be able to zoom out on the handwrite area.
Now, the MT/CT Editor will be open on keyboard mode when using an iOS device by default.
If the user use Safari and doesn't zoom, the page will be opened in handwrite mode. This will not happen in Chrome, as I didn't found a way to detect the zoom level of the page.
1. Open a demo on `html-integrations`
2. With an iOS device, navigate to the opened demo using Safari
3. Zoom the web page
4. Open the MT Editor
The MT Editor will be opened in Keyboard mode
5. Close the MT Editor
6. Reset the page
7. Open the MT Editor without zooming the page
The MT Editor will be opened in Handwrite mode
---
[#taskid …

fix: open MT/CT Editor in Keybord mode when using iOS

---

CHANGES.md
demos/angular/generic/package.json
demos/angular/tinymce5/package.json
demos/html5/ckeditor4/webpack.config.js
demos/html5/ckeditor5/webpack.config.js
demos/html5/froala/webpack.config.js
demos/html5/froala2/webpack.config.js
demos/html5/generic/webpack.config.js
demos/html5/tinymce4/webpack.config.js
demos/html5/tinymce5/webpack.config.js
demos/html5/tinymce6/webpack.config.js

Chage webpack demo host to localhost. Windows doesn't display the demos when using the IP 0.0.0.0. Using `localhost` will work on Linux and Windows.
In IPv4 the address 0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown or non applicable target. However, for practical reason, many client software treat 0.0.0.0 as localhost. For this reason we have decided to use `localhost` directly.
1. Run a demo.
2. Check if the url use localhost
---
[#taskid 21894](https://wiris.kanbanize.com/ctrl_board/2/cards/21894/details/)

fix: change webpack demo host to localhost

---

CHANGES.md
packages/mathtype-ckeditor5/src/plugin.js
packages/mathtype-html-integration-devkit/package.json
packages/mathtype-html-integration-devkit/src/latex.js
packages/mathtype-html-integration-devkit/src/parser.js
packages/mathtype-html-integration-devkit/src/util.js

When an `<img>` or malicious HTML code is encapsulated inside a <math> tag, can bypass the CKEditor security filters, causing a vulnerability.
Browser engines are parsing HTML differently based on the given content namespace which is figured out e.g. by recognizing specific unique elements. Overall, the whole HTML page is recognized as HTML namespace by default and parsed by a browser engine in a well-known pattern. So the HTML like:
```
<div>
<style>
</style>
</div>
```
will be parsed as:
```
<HTML div>
<HTML style>
#text: <img src onerror="alert(1)">
```
However, in the case of these both namespaces:
MathML, recognized by using math element
SVG, recognized by using svg element
The style element content will be parsed as a normal HTML, not a text. So, as an example replacing div element …

fix: add dompurify dependency and sanitize mathml to prevent XSS

---

demos/angular/froala/README.md
demos/react/froala/README.md
packages/froala/README.md
packages/froala/wiris.src.js

The MT/CT Editor is not focused when it is opened by clicking in the MT/CT icon in the Contextual Toolbar in the HTML Editor.
The root of the issue resides in the way Froala handles the contextual toolbar. Since fixing the focus can not be done on our side, the best solution, also recommended by the Froala support team, is to disable the contextual toolbar on formulas.
This means that the existing formulas can only be edited by double click.
1. Open the latest Froala demo.
2. Try to open a new or existing formula in all the possible ways.
3. Validate that, once the modal is opened, you can type on it without manually focusing.
---
[#taskid 26198](https://wiris.kanbanize.com/ctrl_board/2/cards/26198/details/)

fix: Autofocus not working

---

packages/tinymce5/editor_plugin.src.js

The MathType filter for Moodle doesn't render LaTex formulas to MathType if they are written in student text fields. Insted, they get corrupted.
This PR solves the mentioned issue with the same behaviour as the Moodle default parser, MathJax, for TinyMCE.
1. Open a new Moodle instance with the changes on this PR.
2. Change to student role.
3. Set TinyMCE as the default editor.
4. In a student field (for example, a forum), write a latex formula.
5. Validate that is rendered properly.
---
[#taskid 4878](https://wiris.kanbanize.com/ctrl_board/2/cards/4878/details/)

[Fix] Latex not rendering on Moodle

---

packages/ckeditor5/src/plugin.js
packages/devkit/src/util.js

Chem equations disappear when you drag them into another position inside the CKEditor. This only happens with the 8.0.0 version of our plugin.
Due an incorrect DOMPurify implamentation on CKEditor5 the ChemType formulas were detected as XSS attacks when dropped.
1. Open CKEditor5 demo.
2. Insert a ChemType formula and text.
3. Drag the ChemType formula to another position.
4. 
---
[#taskid 30339](https://wiris.kanbanize.com/ctrl_board/2/cards/30339/details/)

fix(ckeditor5): chemtype formulas Drag & Drop

---

demos/html/froala/index.html
packages/ckeditor4/plugin.src.js
packages/ckeditor5/src/plugin.js
packages/devkit/src/stringmanager.js
packages/froala/wiris.src.js
packages/generic/wirisplugin-generic.src.js
packages/tinymce5/editor_plugin.src.js
packages/tinymce6/editor_plugin.src.js

The mathtype integration with mathtype plugin, do not update the tooltip language.
The editor and mathtype modal are both in the specified language while the toolbar buttons are shown in English.
This PR fixes the mentioned issue by:
* Changing the icon wiris translator to take into account any specified language.
* Updates the editors button definition by making the tool-tip parameter dynamic.
The steps have to be done on all demos, except the CKEditor5.
1. Follow the editor instructions to change its language.
2. Uncomment the language settings on the editor Wiris demo.
3. Build and open the demo in development mode.
4. Verify that the Wiris icons tool-tip is in the editor language.
---
[#taskid 15517](https://wiris.kanbanize.com/ctrl_board/2/cards/15517/details/)

Solve language changes don't apply to MT plugins integration icons

---

packages/devkit/src/integrationmodel.js
packages/devkit/src/modal.js

Vite is unable to resolve the routes starting by `!!raw-loader!`
We use the `!!raw-loader!` prefix to import the close, minimize and maximize `svg` for the MathType editor on the devkit package. However, this prefix is not necessary.
Remove the `!!raw-loader!` on the imports from `devkit/modal.js` file will fix the issue.
- Open a demo:
- Build package using `nx build <editor>`
- Start package using `nx start <framework-editor>`
- Open MathType Editor.
- Validate that the close, minimize and maximize buttons from MathType Editor appears correctly.
---
[#taskid 29970](https://wiris.kanbanize.com/ctrl_board/2/cards/29970/details/)

[KB-29970] Remove !!raw-loader! prefix for Vite compatibility

---

CHANGES.md
demos/angular/generic/src/app/app.component.ts
demos/html/generic/src/app.js
demos/react/generic/src/index.js

In Staging we need all demos to be in English for the automation tests but the Generic one was in Spanish. This PR fixes the Generic language in both staging and development demo for all the frameworks.
Go to the following links, the staging ones, and verify that demo language is english:
* [HTML5 demo](https://integrations.wiris.kitchen/KB-31349/html/generic/)
* [Angular demo](https://integrations.wiris.kitchen/KB-31349/angular/generic/)
* [React demo](https://integrations.wiris.kitchen/KB-31349/react/generic/)
---
[#taskid 31349](https://wiris.kanbanize.com/ctrl_board/2/cards/31349/details/)

Set Generic demo language to English in Staging

---

packages/devkit/src/contentmanager.js
packages/devkit/src/modal.js

Minimize, maximize, stack and close buttons on the top right of the modal editor were not accessible through the Keyboard, and therefore made the MathType not user-friendly. This PR fixes the issue by changing the logic of the Keyboard interaction with these buttons.
1. Install dependencies with `yarn`.
2. Build the desired package with `nx build <PACKAGE>`.
3. Start the desired demo with `nx start html-<PACKAGE>`.
4. Verify that the top right buttons are accessible through the keyboard. Verify that they work. Verify that once the modal is minimized or maximized, the buttons are also working
> Since the issue is reproducible in all packages and demos, it'll be preferible to perform the tests in more than one demo & package.
---
[#taskid …

Make control buttons accessible for Keyboard

---

CHANGES.md
demos/html/tinymce5/index.html
demos/html/tinymce5/webpack.config.js
demos/html/tinymce6/index.html
demos/html/tinymce6/webpack.config.js
yarn.lock

Currently, Tinymce5 & 6 demos copy the Tinymce module to the dist folder in order to adapt demos for static deployment. Both plugins use the same module folder name (tinymce in the dist folder). NX detects as the folders as the same workspace in two different places and throws an error message.
Changing the module folder names on each Tinymce fix the issue.
1. Install dependencies with yarn
2. Execute:
```
nx build tinymce5
nx start html-tinymce5
nx build tinymce6
nx start html-tinymce6
```
3. Close both demos
4. Try to restart any demo.
---
[#taskid 31663](https://wiris.kanbanize.com/ctrl_board/2/cards/31663/details/)

KB-31663: TinyMCE 5 & 6 demos share module and confuses Nx

---

CHANGES.md
packages/devkit/src/util.js

MathType for CKEditor5 use DOMPurify to remove XSS Injections using Mathml.
DOMPurify is removing the `semantics` and `annotation` tags from our formulas and the value `toolbar` added to the `annotation` tag. We need to configure DOMPurify to accept these elements.
1. Open CKeditor5 demo
2. Open the inspector and execute the next code on the console.
```
window.editor.setData('<math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msqrt><mi>a</mi><mi>a</mi></msqrt><mi>h</mi><mi>e</mi><mi>l</mi><mi>l</mi><mi>o</mi><mfenced><mtable><mtr><mtd><mi>a</mi></mtd><mtd><mi>b</mi></mtd></mtr><mtr><mtd><mi>c</mi></mtd><mtd><mi>d</mi></mtd></mtr></mtable></mfenced></mrow><annotation encoding="application/vnd.wiris.mtweb-params+json">{"language":"en","toolbar":"<toolbar …
```

DOMPurify is removing semantics and annotation Tags.

---

packages/generic/wirisplugin-generic.src.js

The icons to open MathType or ChemType in the generic plugin don't have an alt text. This is necessary for accessibility reasons, so this PR adds the alt text to the MT and CT buttons
1. Install dependencies with `yarn`.
2. Build the generic plugin with `nx build generic`.
3. Open any Generic demo with `nx start <FRAMEWORK>-generic`.
4. Focus on the MT and CT buttons and verify if they have the alt text.
---
[#taskid 30748](https://wiris.kanbanize.com/ctrl_board/2/cards/30748/details/)

fix: Add alt to buttons on Generic

---

packages/devkit/src/core.src.js

Fix a bug that stopped the front end from using the language set in configuration.ini.
Open a demo from the plugins project and modify the configuration.ini to use a language different than the default one. The language of the modal and the editor should be that defined in the configuration.ini file. Detailed instructions can be found on the associated card.
---
[#taskid 30880](https://wiris.kanbanize.com/ctrl_board/2/cards/30880/details/)

Fix language not being read from server editor parameters

---

CHANGES.md
packages/devkit/src/integrationmodel.js
packages/devkit/src/popupmessage.js

This PR improves the way we treat the caret comes back when editing formulas.
* The caret focused on the editor when clicked on the Cancel + Cancel button.
* The caret didn't come back when editing an existing formula, instead it selected the formula.
1. Install dependencies with `yarn` and build the desired package with `nx build <PACKAGE>`.
2. Open the desired demo with `nx start html-<PACKAGE>`
3. Place the caret anywhere in the HTML Editor.
4. Click on the MT/CT icon.
5. Insert any formula in the MT/CT Editor.
6. Click on Cancel in the MT/CT Editor.
7. Click on Cancel in the Confirmation Dialog.
8. Verify that the caret is in the Modal Editor.
9. Click on Cancel in the MT/CT Editor.
10. Click on Close in the Confirmation Dialog.
11. Make sure that the focus comes back.
---
[#taskid …

Fix caret issues when interacting with the Close Modal

---

packages/devkit/package.json
packages/devkit/src/telemeter.js

Added the new Telemetry Class in the Devkit package. This class could be used to start and close sessions with the wiris telemeter.
Telemeter class have two static funtions:
- **static init(telemeterAttributes):** Start a session with the Telemeter. The `telemeterAttributes` expects three params, a **host**, a **solution** and a **config**. (Check example on Quick Start).
- **static async finish():** Close the session with the Telemeter
A solution is defined by:
* **name**: Use the right name from the [Solutions list](https://docs.google.com/document/d/11J17P82BtAX74YZY8BzuFYYO611IfoZNNo19qpPCAR8)
* **version**: The version of the solution.
The host is defined by:
* **nam**: Some data about the environment.
* **fam**: The family of the data written in **nam**.
* **ver** (optional): The …

[KB-30453] Add telemer class for devkit

---

docs/development/compiling/README.md

`SERVICE_PROVIDER_URI` was misspelled as `SERVICE_PROVIDER_URL`.
---
[#taskid 30785](https://wiris.kanbanize.com/ctrl_board/2/cards/30785/details/)

[KB-30785] Fix typo in compilation instructions

---

demos/angular/generic/src/index.html
demos/html/generic/index.html
demos/react/generic/public/index.html
packages/devkit/src/modal.js
packages/devkit/src/popupmessage.js
packages/res/demos/index.html
yarn.lock

This PR adds data-testid attributes to a series of components in MathType and in the demos in order to facilitate the automation of testing.
1. `yarn`, `nx build <PACKAGE>`, `nx start <FRAMEWORK>-<PACKAGE>` to start a demo.
2. Use the inspector to check that all the elements listed in the list of testids do have the correct testid.
The list of testids can be found in a link in the Kanbanize card for this issue. 
---
[#taskid 29495](https://wiris.kanbanize.com/ctrl_board/2/cards/29495/details/)

[KB-29495] Add data-testid attributes

---

CHANGES.md
demos/html/generic/src/app.js

The Generic demo have the editor next language configurated:
```js
const mathTypeParameters = {
editorParameters: { language: 'en' }, // MathType config, including language
};
```
The `editorParameters` are also saved inside an annotation tag on each formula. This is causing incompatibilities with tests on generic demo, as the other demos doesn't have this configuration. For consistency, this PR remove the language configuration from generic demo.
1. Open generic demo.
2. Insert a formula.
3. Open the browser inspecto.
4. Check that the inserted formula doesn't have the annotations tag.
---
[#taskid 32550](https://wiris.kanbanize.com/ctrl_board/2/cards/32550/details/)

KB 32550 - Remove language configuration on Generic demo

---

CHANGES.md
packages/devkit/src/contentmanager.js
packages/devkit/src/modal.js
yarn.lock

When users open the MathType editor with a desktop window smaller than 550 px width, the MathType detects as user is on mobile. This PR fix this issue detecting correctly If user is on Desktop.
1. Open a demo from `html-integrations`.
2. Reduce the screen to the minimum.
3. Press the MathType icon to insert an equation.
The MathType editor will be open correctly.
---
[#taskid 33529](https://wiris.kanbanize.com/ctrl_board/2/cards/33529/details/)

[KB 33529] - Editor becomes unusable when reducing the screen to 550px width

---

CHANGES.md
packages/devkit/src/mathml.js

An extra blank space is added in the MathML between "math" and "xmlns" when editing a ChemType formula and converting it to a MT formula:
```
«math  xmlns=¨http://www.w3.org/1998/Math/MathML¨»«msqrt»«mi»x«/mi»«/msqrt»«....
```
- Open the HTML demo for Generic.
- Type CTRL+A + DELETE (it deletes everything in the HTML Editor)
- Insert a ChemType formula
- Type CTRL+A (it selects the ChemType formula in the HTML Editor)
- Click on the MT button in the HTML Editor (it opens the MT Editor containing the ChemType formula in it)
- Delete the ChemType formula in the MT Editor
- Type a MT formula, for example, "square root of x" in the MT Editor.
- Click on the Insert button in the MT Editor (the formula is inserted in the HTML-Editor)
The MathML of the formula is the next one (it has two blank …

[KB-32826] fix: don't add an extra whitespace between <math and xmlns

---

CHANGES.md
docs/README.md
packages/devkit/src/contentmanager.js
packages/devkit/src/modal.js

This PR adds two global Events on Devkit module to capture when the MathType/ChemType editor is open/close.
- `onModalOpen()` Triggered when MT/CT editor modal is open
- `onModalClose()` Triggered when MT/CT editor modal is close
1. Add next code inside `app.js` from any demo, after editor is created:
```js
let modalOpenListener = window.WirisPlugin.Listeners.newListener('onModalOpen', () => {
console.log('onModalOpen');
});
window.WirisPlugin.Core.addGlobalListener(modalOpenListener);
let modalCloseListener = window.WirisPlugin.Listeners.newListener('onModalClose', () => {
console.log('onModalClose');
});
window.WirisPlugin.Core.addGlobalListener(modalCloseListener);
```
2. Open the demo.
3. On the demo, open the browser inspector.
4. Open MathType editor.
A console log with the text …

KB 32324 - Add open/close MT/CT Editor global events.

---

CHANGES.md
packages/devkit/src/serviceprovider.js

This PR adds the front-end logic to append and pass custom headers to our API requests. This new feature, should not change the way our requests work.
1. Go to the `wepack.config.json` file of the demo you want to try and set the following parameters:
```
'SERVICE_PROVIDER_URI': demo_url,
'SERVICE_PROVIDER_SERVER': backend,
```
Where a backend example could be `'php'` and a demo_url is the one where the demo is running, for example: `'http://localhost:8080/plugin/3.50/generic-demo/generic_wiris/integration/'`.
2. Build and open a demo using the plugins project.
3. Add the desired custom headers and its values to the `configuration.ini` file.
4. Validate that the API requests you make contain those headers.
---
[#taskid 34463](https://wiris.kanbanize.com/ctrl_board/2/cards/34463/details/)

Add custom headers to API requests

---

demos/html/ckeditor5/src/app.js
packages/ckeditor5/src/plugin.js

When user set a custom toolbar with the buttons `<` or `>`, for example:
```
"<toolbar ref='general'><tab ref='symbols' empty='true'><section rows='3'><item ref='&gt;' extra='false'/></section></tab></toolbar>"
```
:warning: We use `&gt;` and `&lt;` instead  `<` and `>` to avoid conflicts with `showimage` service. 
The custom toolbar xml is added on the `<annotation>` tag from inserted formulas.
CKEditor5 convert the `&gt;` and `&lt;` to `<` and `>` again, causing issues with `showimage` service on users that have custom tags with this two buttons set when they use the getData() function.
This issue have been fixed on this PR and now the special characters are converted to HTML Entity (decimal) when using getData() function.
1. Set next custom toolbar on editorParameters on CKEditor5: …

fix: convert special symbols to entities when using ck5 getData()

---

CHANGES.md
packages/ckeditor4/plugin.src.js

When dragging and dropping a formula from a window to another in CKEditor 4, the formula is not editable. 
This happens because when copy & paste or drag & drop formulas from one window to another, it does not copy the class or ID of those, hence the new pasted formula is not detected as a formula but as a plain image.
To fix the issue, we call the `initParse` function whenever we paste a formula to the editor.
1. Open the staging demo in two different windows in the Chrome browser.
2. Copy or drag the quadratic formula from a window and paste it in the other.
3. Double-click the pasted formula.
4. The MT window should open, and the formula should be editable.
---
[#taskid 24226](https://wiris.kanbanize.com/ctrl_board/2/cards/24226/details/)

fix(CK4): Drag&Drop formula between windows not editable

---

CHANGES.md
packages/ckeditor5/src/plugin.js

In CKEditor5, copy and pasted formulas written with hand opened on the regular editor, not the hand mode.
This was because of a configuration that deleted the information of the formula about the handwriting.
1. Go to the CKEditor5 staging demo.
2. Write and insert a formula in hand mode.
3. Copy & paste the formula.
4. Open the copied formula and validate that the editor opens in hand mode.
---
[#taskid 32892](https://wiris.kanbanize.com/ctrl_board/2/cards/32892/details/)

Fix Copy&Paste formulas written in hand to open in hand mode

---

CHANGES.md
packages/ckeditor5/src/plugin.js
packages/devkit/src/integrationmodel.js

Two objects from our CK5 plugin (ClassicEditor and CKEditor5Integration) are not been correctly destroyed by the garbage collector the first time that a CK5 Editor is destroyed. This two objects are created again when the editor is recreated. This just happen the first time that the editor is recreated.
Use this demo from [integrations-sandbox](https://github.com/wiris/integrations-sandbox/tree/KB-17299) using the branch **KB-34718** to destroy and recreate the CKEditor5.
1. Open the `integrations-sandbox/compositions/html5/ckeditor5-memory-leak-demo` demo.
2. Change the src code from `node_module/@wiris/...` packages from the src code from this PR.
3. Open the inspector and go to the Memory page.
4. Make a Snapshot.
5. Press the Reload CKEditor button. The editor will be destroyed and …

fix: ck5 memory leak with ClassicEditor

---

packages/ckeditor5/src/plugin.js
packages/devkit/src/util.js
yarn.lock

DOMPurify is removing the attr linebreak from CK5 pasted formulas. This PR configures DOMPurify to ignore this attribute.
1. Create a formula with some breaklines.
2. Copy the formula
3. Paste the formula
The linebreaks are not removed.
---
[#taskid 34777](https://wiris.kanbanize.com/ctrl_board/2/cards/34777/details/)

[KB-34777] Fix, stop deleting linebreak attr by DOMPurify on CK5

---

packages/tinymce6/editor_plugin.src.js

This PR add changes to tinymce6 plugin to make it compatible with new TinyMCE6 Moodle plugin. You can test this PR on Moodle 4.1 using the plugin [moodle-tinymce6_wiris](https://github.com/wiris/moodle-tinyMCE6_wiris). The plugin use the changes from this PR.
1. Open Moodle 4.1.
2. On Moodle Administrator page set TinyMCE6 as default editor and disable Cachejs.
3. Inside Moodle folder: `...MOODLE_401_STABLE/lib/editor/tiny/plugins/` create a folder named `wiris`.
4. Inside the created `wiris` folder add all the code from the repository [moodle-tinymce6_wiris](https://github.com/wiris/moodle-tinyMCE6_wiris).
5. Log In on Moodle as Admin and create a course.
6. Try to insert/edit formulas using the TinyMCE6 MathType plugin from Description section.
---
[#taskid …

feat: tinymce6 for moodle compatibility

---

demos/html/tinymce6/src/app.js

Now the previous inserted handwritte formulas doesn't lose the annotations tags.
1. Open the tinymce6 demo
2. Open the handwritte formulas
The editor is open in hand mode
---
Closes #X (*Associated GitHub issue, if any*)
[#taskid 34309](https://wiris.kanbanize.com/ctrl_board/2/cards/34309/details/)

fix: demo handwritte formulas open in hand mode

---

CHANGES.md
packages/devkit/src/util.js

When the caret was at the beginning of the editor where there's a formula, instead of opening a new formula, it edits the one on top. This PR fixes the mentioned behavior by changing the nodes where the formulas should be added.
This bug was happening also in between 2 formulas when they were at the beginning of the editor.
1. Install dependencies with `yarn`.
2. Build the desired demo with `nx build <PACKAGE>`.
3. Start the demo with `nx start html-<PACKAGE>`.
4. Empty the content of the text area.
5. Insert a formula.
6. Place the caret at the beginning of the text are and insert a formula.
7. Verify that when clicking on the MT/CT button, the first formula was not being edited. Verify also that the new added formula is placed where it should.
> The issue was present on all editors but …

Fix strange behavior when the caret at the beginnig

---

CHANGES.md
packages/devkit/src/telemeter.js

This bug was detected on CKEditor5 with Vue but the fix can prevent future issues. When user open for first time a Vue page with multiples CKEditor5 the telemeter init could be executed multiple times too. This is causing the next runtime error:
```
telemeter_wasm.js:784 [Telemeter] Module ready (3 times)
closure invoked recursively or destroyed already
at imports.wbg.__wbindgen_throw (webpack-internal:///./node_modules/@wiris/mathtype-html-integration-devkit/telemeter-wasm/telemeter_wasm.js:841:15)
at [http://localhost:8080/b92b3f8760238484.wasm:wasm-function[1073]:0x4726b](http://localhost:8080/b92b3f8760238484.wasm:wasm-function%5B1073%5D:0x4726b)
at [http://localhost:8080/b92b3f8760238484.wasm:wasm-function[920]:0x45fc8](http://localhost:8080/b92b3f8760238484.wasm:wasm-function%5B920%5 …
```

Prevent generate multiple instances of Telemeter

---

packages/ckeditor5/src/integration.js
packages/ckeditor5/src/plugin.js

CKEditor5 Team detected the bug https://github.com/ckeditor/ckeditor5/issues/14106:
> Currently, when non-defualt font properties are selected, and then a widget (e.g. image, math formula) is inserted into the document, the font reverts back to its default state.
> 
> This behavior could be improved in such a way, that the selected font family, size, background color etc. would be preserved upon inserting a widget.
This PR adds CKEditor Team proposed changes to work better with the recent improvements on CKEditor5.
> The CKEditor5 is fixed on the latest release of `@ckeditor/ckeditor5-engine` but this improvement will work correctly on oldest versions.
1. Use the latest `@ckeditor/ckeditor5-engine` package from the CKEditor 5 repository (because the fix for the bug linked above has not …

fix (ckeditor5): improve inline widget insertion

---

demos/html/tinymce6/src/app.js
packages/ckeditor4/plugin.src.js
packages/ckeditor5/src/integration.js
packages/devkit/src/image.js
packages/froala/wiris.src.js
packages/generic/wirisplugin-generic.src.js
packages/tinymce5/editor_plugin.src.js
packages/tinymce6/editor_plugin.src.js

In TinyMCE 6, formulas lose alignment when clicked.
In Froala, formulas added in the demo by default came without proper alignment.
This PR fixes both of these issues.
1. Open up the TInyMCE 6 and Froala demos.
2. Check that the formulas are properly aligned
3. Click on any formula, and check that it stays aligned.
---
[#taskid 34325](https://wiris.kanbanize.com/ctrl_board/2/cards/34325/details/)

Alignment issues in TinyMCE 6 and Froala

---

CHANGES.md
packages/devkit/src/util.js

This PR fixes an issue where the default formulas were being opened with the ChemType modal on CKEditor5 demos. The bug was caused by the DOM purify, which removed the attributes in charge of differentiating if the formula was Math or Chem.
1. Open the CKEditor5 demo.
2. Validate that the ChemType formulas are opened with the CT modal on double-click.
---
[#taskid 36421](https://wiris.kanbanize.com/ctrl_board/2/cards/36421/details/)

Fix that the default formulas were opened with ChemType

---

packages/viewer/docs/spec.md
packages/viewer/index.html
packages/viewer/src/app.ts
packages/viewer/src/latex.ts
packages/viewer/src/mathml.ts
packages/viewer/src/properties.ts
packages/viewer/src/retro.ts

When we released the new Viewer, it didn't have the exact same API for the final user as the old one. Unfortunately our demos from plugins, and possibly some clients, use these old APIs (exposed through the global object `com.wiris.js.JsPluginViewer` inside `window`).
This PR adds a retrocompatibility layer with this old API, in particular it adds the following public methods:
- `parseSafeMathMLElement`
- `parseDocument`
- `parseElement`
- `parseLatexElement`
- `parseLatexDocument`
Respecting as much as possible their old signatures, now typed with TypeScript instead of Haxe.
Nonetheless, most of the arguments for these methods will be ignored, as honoring them would require a deep reworking of the new Viewer to make it, essentially, a clone of the old one.
As a technicism, this …

[KB-36582] Add missing retrocompatibility with the com.wiris.js.JsPluginViewer API

---

.github/workflows/deploy-staging.yml
.gitignore
demos/angular/froala/src/app/app.component.css
demos/angular/froala/src/app/app.component.ts
demos/angular/froala/src/environments/environment.prod.ts
demos/angular/froala/src/environments/environment.ts
demos/html/froala/src/app.js
demos/html/froala/src/static/style.css
demos/html/froala/webpack.config.js
demos/react/froala/src/index.css
demos/react/froala/src/index.js
demos/vue/tinymce-vue-demo/package.json
scripts/createEnvFile.js

This PR gets the froala api key from github secrets when deploying the [staging demos](https://integrations.wiris.kitchen/stable/html/froala/).
If we don't set the api key the froala editor will self-destruct after a while when not using the localhost.
---
[#taskid 36829](https://wiris.kanbanize.com/ctrl_board/2/cards/36829/details/)

Get froala api key from secrets on staging

---

packages/devkit/src/util.js

This PR fix a CKEditor4 bug that doesnt allow to open MT Editor after inserting LaTeX and deleting all editor content.
1. Open the [demo](https://integrations.wiris.kitchen/master/html/ckeditor4/)
2. Type a LaTeX formula
3. Click on Update
4. Delete all the content in the HTML Editor (CTRL+A and DELETE)
5. Click on the MT Button
---
[#taskid 37748](https://wiris.kanbanize.com/ctrl_board/2/cards/37748/details/)

CKEditor4 - MT doesn't open after inserting LaTeX and deleting all editor content

---

packages/devkit/src/contentmanager.js

The focus was lost on the way, when opening the MathType modal after the first time, due to WordPress doing.
This task fixes it and makes focus go back to the MathType modal.
1. Follow the instructions on the [MathType for WordPress](https://github.com/wiris/mathtype-wordpress) project to start a new instance.
2. Install dependencies on `html-integrations` with `yarn install`.
3. Build the TinyMCE package with `nx build tinymce5`.
4. Copy the `plugin.min.js` generated file from the `html-integrations/packages/tinymce5` to the `mathtype-wordpress/build` folder.
5. Refresh or start a new page on WordPress.
---
[#taskid 35995](https://wiris.kanbanize.com/ctrl_board/2/cards/35995/details/)

Fix the WordPress focus on MT that was lost

---

.github/workflows/deploy-staging.yml
.github/workflows/dismantle-staging.yml
staging/branch/angular/index.html
staging/branch/html/index.html
staging/branch/index.html
staging/branch/react/index.html
staging/root/index.html
staging/root/styles.css

This PR adds browsing pages to the staging environment.
It adds the following pages:
https://integrations.wiris.kitchen/index.html
https://integrations.wiris.kitchen/$BRANCH/index.html
https://integrations.wiris.kitchen/$BRANCH/html/index.html
https://integrations.wiris.kitchen/$BRANCH/angular/index.html
https://integrations.wiris.kitchen/$BRANCH/react/index.html
for each branch $BRANCH that stems from branch KB-36808 (or from master once KB-36808 is merged to master).
These pages contain navigation links to browse to each demo and even through different branches.
You can check https://integrations.wiris.kitchen/KB-36808 to see if all the links work properly.
To test that the creation and destruction of branches is properly reflected in https://integrations.wiris.kitchen/, you can follow …

[KB-36808] Add browsing pages to staging

---

packages/ckeditor4/package.json
packages/ckeditor5/package.json
packages/ckeditor5/src/plugin.js
packages/froala/package.json
packages/generic/package.json
packages/tinymce5/package.json
packages/tinymce6/package.json

The hand formulas MathML was not filtered due to CKEditor5 `get` method.
This PR solved the issue by changing the CKEditor5 `get` method and parsing the retrieved data to create the image formulas and then to get the MathML filtered by us.
1. Insert a Hand formula. E.g., 5,6
2. Insert the same formula using the keyboard (without Hand).
3. Click the update button.
4. Compare the MathML between the generated formulas (Keyboard, Hand). They should match.
---
[#taskid 37876](https://wiris.kanbanize.com/ctrl_board/2/cards/37876/details/)

Fix hand formulas MathML is not filtered

---

packages/viewer/src/app.ts

This PR fixes a bug that stops MathType from allowing to edit LaTeX formulas when the new viewer is being used.
The issue can currently only be reproduced in the plugins demos, not on the html-integrations ones. The reason is that the plugins demos take the compiled viewer (WIRISplugins.js), whereas html-integrations uses the one from www.wiris.net, which is the old version (using Haxe). The new viewer has a feature which rerenders the formulas upon modifying the DOM, so when MathType inserts LaTeX, the viewer tries to render it and causes an error.
The proposed solution is to temporarily disable this feature, in order to solve the bug immediately, and reimplement it taking this bug into account.
1. Start any plugins demo (`cd docker/build`, `EDITOR=<editor> docker compose run <tech>`, …

[KB-37834] fix: MathType with the new viewer could not edit LaTeX

---

docs/development/compiling/README.md
docs/development/demos/README.md
packages/devkit/doc/src/getting_started.md
packages/devkit/doc/src/services_generic.md
packages/generic/README.md
packages/generic/getting_started.md
packages/generic/services.md

This PR updates the documentation on:
* How to build the plugins.
* How to run the demos in development mode.
These instructions were outdated and missing some information.
* Validate that the documentation is clear and understandable.
* Validate that there's no missing information regarding the matters of the updated documentation.
* Validate that the updated steps are working.
---
[#taskid 39052](https://wiris.kanbanize.com/ctrl_board/2/cards/39052/details/)

Update development instructions

---

CHANGES.md
packages/ckeditor5/src/plugin.js

The CKEditor 5 `setData` method was unable to understand MathML LaTeX formulas and resulted in error. This PR fixes the behavior by transforming MathML LaTeX formulas into LaTeX notation before inserting the content in the editor.
1. Open the CKEditor5 staging demo.
2. Add the following text on the editor: `hello $$\sqrt 1$$`
3. Add a formula if there's none.
4. Open the Console inspector and run the following command: `editor.setData(editor.getData())`.
5. The previous commands set the editor content in the editor, so it should be the same.
6. Try also to run the following command:
```
editor.setData('<p>MathType - Keyboard:&nbsp;<math><msqrt><mi>x</mi></msqrt></math></p><p>MathType - Handwriting:&nbsp;<math><semantics><mfrac><mi>x</mi><mn>3</mn></mfrac><annotation …
```

Fix setData on CKEditor5 not understanding math LaTeX formulas

---

CHANGES.md
packages/ckeditor5/src/plugin.js
packages/devkit/src/util.js

DomPurify is not taking into account the `open` and `close` attributes from the `mfenced` MathML tag. This PR adds the mentioned attributes to the list of trusted attributes of DomPurify.
DomPurify also replaces the `&lt;` and `&gt;` values for `<` and `>`, which are not rendered by our `showimage` service, when these are values from an attribute.
1. Open CKEditor5 demo.
2. Create a formula with the open and close braces (`<`, `>`).
3. Drag and drop the formula.
4. No error should appear, and the formula should be correctly rendered on the place it was dropped.
---
[#taskid 39549](https://wiris.kanbanize.com/ctrl_board/2/cards/39549/details/)

Fix DomPurify replacing undesired tags

---

CHANGES.md
packages/ckeditor5/src/plugin.js

`editor.getData()` returns null when using formulas with '<' and '>' because CK5 replaces `&lt;` and `&gt;` for the previous characters, which our viewer can not render properly.
This PR fixes that by forcing a replacement of the characters that we can't render for the ones that we can.
1. Go to the CKEditor5 demo.
2. Insert a bracket angles formula: 
3. Open the console inspector with ctrl + shft + I
4. Click on the update button
5. No error on the console should appear, and the formula should be rendered as expected on the update area.
---
[#taskid 40736](https://wiris.kanbanize.com/ctrl_board/2/cards/40736/details/)

fix(ck5): getData returning null

---

packages/viewer/src/app.ts
packages/viewer/src/properties.ts

This PR avoid unnecesary request made by the viewer. We found that the viewers installed locally on the Integration Services are not using the Integration Services and are making request to the wiris.net. 
To mitigate this, the updated viewer now detects its context within the integration services, to dynamically modify the default services endpoint accordingly.
Additionally, this pull request checks If  the viewer is already loaded to prevent duplicate requests. This is especially relevant in scenarios where there might be more than one viewer script inserted into the DOM.
To validate the changes, follow these steps using a PHP Integration Services demo with CKEditor 4:
1. Deploy a demo from the plugins repository with PHP and CKEditor 4
2. Switch to branch KB-41112 in the …

avoid unnecesary request made by the viewer

---

demos/html/viewer/index.html
packages/viewer/src/mathml.ts

This PR update the viewer in order to decode `Safe MathML` to `MathML`. This is necesary for moodle filter plugin as the safe mathml rendering from Moodle is not working when using the new viewer.
1. Use wiris-moodle-docker and deploy `MOODLE_403_STABLE`.
2. Configure MathType filter to use the render option: `Client`.
3. If you have moodle volume on `/html/var/MOODLE_403_STABLE` you can use this webpack.config.js example to build viewer directly to the moodle-filter_wiris plugin:
```
const path = require('path');
module.exports = (config, context) => {
return {
entry: './src/app.ts',
mode: 'none',
devtool: 'inline-source-map',
module: {
rules: [
{
test: /\.tsx?$/,
use: 'ts-loader',
exclude: /node_modules/,
},
{
test: /\.js$/,
exclude: /node_modules/,
use: ['babel-loader']
},
],
}, …
```

feat(viewer): decode safe mathml

---

demos/html/generic/src/app.js
packages/devkit/src/contentmanager.js
packages/devkit/src/core.src.js
packages/devkit/src/integrationmodel.js
packages/generic/wirisplugin-generic.src.js

This PR includes a mechanism to force the editor to be opened in hand mode.
To activate this feature, you'll need to modify how the Wiris editor is initialized. You can do so modifying line 26 in `app.js`:
```
window.wrs_int_init(editableDiv, toolbarDiv, undefined, { forcedHandMode: true }); // will activate forced hand mode
```
You can try this other modifications to experiment the different behaviours:
```
window.wrs_int_init(editableDiv, toolbarDiv); // won't activate forced hand mode
window.wrs_int_init(editableDiv, toolbarDiv, undefined); // won't activate forced hand mode
window.wrs_int_init(editableDiv, toolbarDiv, undefined, {}); // won't activate forced hand mode
window.wrs_int_init(editableDiv, toolbarDiv, undefined, { forcedHandMode: false }); // won't activate forced hand mode …
```

feature: Include mechanism to force hand mode when editor is opened

---

packages/viewer/README.md
packages/viewer/package.json
packages/viewer/project.json
packages/viewer/webpack.config.js

This PR change the webpack configuration from viewer package in order to create a production build instead a development build. Also I added a script to create a development build `nx build-dev viewer` in case we want to work/debug the viewer.
1. Build the viewer for production using command:
```
yarn
nx build viewer
```
2. Check If the viewer works correctly using the **index.html** from the viewer package.
---
[#taskid 39494](https://wiris.kanbanize.com/ctrl_board/2/cards/39494/details/)

Viewer build production mode

---

CHANGES.md
packages/froala/wiris.src.js

Froala creates `id` for the MathType and ChemType buttons, taking into account the current instance ID. When applying the buttons hover text according to the set language, we use those IDs. This PR fixes the fact that they were static instead of dynamic, as Froala does.
1. Change the Froala editor language.
2. Start the Froala demo.
3. Hover over the MathType or ChemType button and check that the text is in the set language.
---
[#taskid 40561](https://wiris.kanbanize.com/ctrl_board/2/cards/40561/details/)

Fix froala id buttons not being dynamic

---

scripts/publish.mjs

The publish workflow (https://github.com/wiris/html-integrations/actions/workflows/publish.yml) is supposed to publish packages on npm and afterwards make a git commit and some git tags, and push them to the origin on GitHub.
Up until now, this step would fail because the workflow was lacking a step wherein the Git user was configured (name and email). I have chosen the name and email used for [cicd-wiris](https://github.com/cicd-wiris) in other projects (see e.g. the commits made by cicd-wiris in https://github.com/wiris/atlas). It's important to notice that, after the change introduced by this PR, the commits are not made by the cicd-wiris *user*, but rather signed with its name and email.
1. Create a branch based off this one.
2. Add a new commit to that branch in which you comment out …

[KB-40681] Configure Git credentials in publish workflow

---

packages/viewer/src/services.ts

Formulas are cached including parameters: centerbaseline, metrics, and lang. However, the new Viewer is not hashing these parameters before initiating the showImage Get request. Consequently, the generated Hash does not align with the Hash saved in the cache by Integration Services. This inconsistency leads to the cache being ignored by the viewer.
1. Add next mathml on the body of `html-integrations/packages/viewer/infex.html`:
```
<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi><mo>=</mo><mfrac><mrow><mo>-</mo><mi>b</mi><mo>&#177;</mo><msqrt><msup><mi>b</mi><mn>2</mn></msup><mo>-</mo><mn>4</mn><mi>a</mi><mi>c</mi></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></math>
```
2. Build the viewer using command `nx build viewer`
3. Open index.html `nx serve viewer`
4. On …

fix(viewer): hash all parameters before sending get showimage request

---

CHANGES.md
packages/viewer/src/utils.ts

Formulas containing the `&` and `"` symbols were breaking; causing console errors and breaking all the following formulas.
The cause was that the mentioned symbols were not being transformed into their HTML Entities, and it caused render issues.
This PR replaces the characters for their corresponding HTML Entity.
1. Create a broken equation for the viewer, such as an empty matrix with latex: 
`$$\begin{pmatrix}&&&\\&&&\\&&&\\&&&\end{pmatrix}$$`
2. Insert equations after the latex.
3. Render the formulas.
4. No error console appears and all the formulas are properly rendered.
---
[#taskid 42230](https://wiris.kanbanize.com/ctrl_board/2/cards/42230/details/)

Fix formulas with '&' symbol not rendereting

---

CHANGES.md
packages/viewer/src/utils.ts

The `<` symbol broke in the latest release (`8.8.1`) of the viewer due to a change which introduced re-decoding some, already decoded, characters. This broke the formulas, hence they could not be rendered.
This PR fixes the issue by avoiding the re-decoding of the `&` character, which was breaking the formulas with the `<` one.
1. Build the viewer with `nx build viewer`
2. Start a demo using the local build viewer.
3. Add a formula containing the `<` character. For example: `3 < 4`.
4. Add a formula containing the `&` character. For example `$$\begin{pmatrix}&&&\\&&&\\&&&\\&&&\end{pmatrix}$$`
5. Click on the update button.
6. All the formulas should render properly.
---
[#taskid 43787](https://wiris.kanbanize.com/ctrl_board/2/cards/43787/details/)

Fix re-decode of formulas when rendering them

---

packages/devkit/src/util.js

Prevents removing all valid attributes from MathML.
**Note:** 'open', 'close', 'class', 'mathvariant' are already valid attributes supported by DOMPurify,  'linebreak' is not. 
Please see original issue.
---
Closes #881

fix: #881 keep valid attrs when sanitizing MathML

---

packages/viewer/index.html
packages/viewer/src/mathml.ts
packages/viewer/src/services.ts

This PR prevents the viewer to make unnecessary mathml2accesible requests if formula is already cached.
1. Build the viewer with `nx build viewer`
2. Navigate to `/package/viewer`
3. Run the command `npm run serve`
4. Reload the page
No service **mathml2accesible** requests appear on the Network tab from the Inspector.
**Note:** As request are made to AWS maybe you will need to make some reloads to the page in order to cache the formula in diferent AWS zones.
---
[#taskid 43670](https://wiris.kanbanize.com/ctrl_board/2/cards/43670/details/)

fix(viewer): prevent mathml2accesible request if formula is cached

---

packages/froala/wiris.src.js

On Froala with inline toolbar, adding equations throws an error that kills the demo. This PR fixes that problem.
1. Modify `demos/html/froala/src/app,js` to add `toolbarInline: true` to the Froala settings.
2. Start a Froala demo (`nx start html-froala`).
3. Test that you can insert and edit MathType formulas.
---
[#taskid 42503](https://wiris.kanbanize.com/ctrl_board/2/cards/42503/details/)

[KB-42503] Froala inline toolbar throws error when inserting equation

---

packages/viewer/src/mathml.ts

If a page to be rendered includes a MathML with an alt text that the `mathml2accessible` service is not capable of generating (e.g. such as a formula containing a `largeop`), it throws an error, and the rest of the equations in the page to be rendered are not rendered. 
1. Open the viewer demo (`nx start html-viewer`).
2. Add the following formula: `<math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mo largeop="true">2</mo><mn>2</mn></msub></math>`.
The formula is rendered normally, but its alt text is not available.
The formula is not rendered and neither are subsequent formulas.
---
[#taskid 42660](https://wiris.kanbanize.com/ctrl_board/2/cards/42660/details/)

[KB-42660] Viewer breaks when a formula's alt text cannot be generated

---

.github/workflows/deploy-staging.yml
.gitignore
demos/html/ckeditor4/src/app.js
demos/html/ckeditor4/webpack.config.js
docs/development/demos/README.md
scripts/createEnvFile.js
yarn.lock

CKEditor4 staging demo stopped working, since the CKEditor4 versions above `23.0.0` require a license. 
**Staging demos**
1. Go to https://integrations.wiris.kitchen/KB-43835/html/ckeditor4/ and validate that the demo is working as expected in the CKEditor4 version `+23.0.0`.
**Local demos**
1. Follow the instructions on the `docs/development/demos/README.md` file to start the demo with the `.env` file for the CKEditor4 API key.
2. Build and start the demo as usual (instructions also on the previous file).
3. Validate that the demo is working as expected with the CKEdtiro4 version `+23.0.0`.
---
[#taskid 43835](https://wiris.kanbanize.com/ctrl_board/2/cards/43835/details/)

Add CKEditor4 license key

---

demos/html/viewer/index.html
packages/viewer/src/app.ts

Use local viewer
1. Open the viewer demo
2. Open the inspector
3. Check that the viewer import request is made on the next endpoint:
http://localhost:4200/node_modules/@wiris/mathtype-viewer/dist/WIRISplugins.js?viewer=image
---
[#taskid 43631](https://wiris.kanbanize.com/ctrl_board/2/cards/43631/details/)

fix: use local viewer

---

packages/ckeditor5/src/plugin.js

Change uses of editor.config.get('language') to integration.getLanguage( ) in the CKEditor 5 package. 
The current code assumes that the editor language config is a string. This is not always the case, as according to the [CKEditor5 documentation](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html#setting-the-language-of-the-content) it can be an object like:
`editor.config.language = {
ui: 'fr',
content: 'en',
...
}`
To reproduce:
1. Have an instance of CKEditor5 with wiris and `editor.config.language = {  ui: 'fr',  content: 'en' }`
2. Once the instance is loaded the warning `Unknown language [object Object] set in StringManager.` will appear and wiris will be in English instead of French.

fix(ckeditor5): use getLanguage to interpret config

---

CHANGES.md
packages/devkit/src/core.src.js

Fix `ncaught TypeError: Cannot read properties of null (reading 'ownerDocument')` error when try to modify a plain text with MT/CT editor, then click cancel
1. Type any string in the HTML editor
2. Select the string typed
3. Click on “Insert equation button”
4. Click on Cancel in the modal
---
[#taskid 44250](https://wiris.kanbanize.com/ctrl_board/2/cards/44250/details/)

Error when try to open plain text with editors

---

CHANGES.md
packages/ckeditor5/src/plugin.js
packages/devkit/src/contentmanager.js
packages/devkit/src/core.src.js
packages/devkit/src/integrationmodel.js
packages/generic/wirisplugin-generic.src.js

This PR move the forceHandMode configuration on the integrationModelProperties. This allow the user to add this configuration for all out integrations using the `mathTypeParameters`.
To test this on tinymce6:
1. On `html-integrations/demos/html/tinymce6/src/app.js` uncomment the `mathTypeParameters` from line 33.
2. Add the `forcedHandMode = true`configuration on `mathTypeParameters`:
```
mathTypeParameters: {
editorParameters: { language: 'de' },
forcedHandMode: true
},
```
3. Open the demo.
Each time you open the MathType editor to create or update a formula, will be automatically open in hand mode.
---
[#taskid 42181](https://wiris.kanbanize.com/ctrl_board/2/cards/42181/details/)

KB 42181 - add forceHandMode configutation on integrationModelProperties 

---

CHANGES.md
packages/devkit/src/integrationmodel.js
packages/froala/wiris.src.js
packages/generic/wirisplugin-generic.src.js

In generic and froala, there is an error in the console: `Uncaught TypeError: Cannot read properties of null (reading 'split')` because when user do double click to a text, the system recognise it as formula image .
After that error is shown, the behavior of the modal is erratic and the user is blocked.
1. Enter to generic and froala staging enviroument.
2. Input a plain text.
3. Double click to that text.
4. Try to edit it with MT/CT. 
5. Ensure that there is no console error.
---
[#taskid 44249](https://wiris.kanbanize.com/ctrl_board/2/cards/44249/details/)

Fix error when double-click a plain text

---

CHANGES.md
packages/devkit/src/util.js

Add some DOMPurify exception in order to avoid error when inserting some formula.
- Open a CKEditor5 demo.
- Type the following equation: `<math xmlns="http://www.w3.org/1998/Math/MathML"><mstack charalign="center" stackalign="right"><mn>2</mn><msrow><mo>+</mo><mn>3</mn></msrow><msline> </msline><mn>5</mn></mstack></math>`
- Once inserted, copy the equation and paste it using the keyboard.
- Check the pasted formula is exactly the same as the original one
---
[#taskid 44372](https://wiris.kanbanize.com/ctrl_board/2/cards/44372/details/)

Add DOMPurify exception

---

CHANGES.md
packages/devkit/src/util.js

Prevent read Wirisformula class from node when don't have it
Fix TypeError when insert a math equation into the first line and edit it with MT/CT
- Insert a math equation into the first line
- Click on Insert math equation. Do not close the modal
- Click on Insert chemistry formula
- Check there is no console error
---
[#taskid 44268](https://wiris.kanbanize.com/ctrl_board/2/cards/44268/details/)

Fix TypeError when insert a math equation into the first line

---

CHANGES.md
packages/devkit/src/core.src.js

Place correct formular position after inserting an equation after a styled text on Ckeditor4. 
- Open any CKEditor 4 plugins demo in Chrome
- Empty the editing area
- Switch to italics, or bold, or underline
- Write some text
- Click the MT or CT icon
- Write a formula and click Insert
- Check that the formula is inserted at the end
---
[#taskid 43453](https://wiris.kanbanize.com/ctrl_board/2/cards/43453/details/)

Place correct formular position 

---

CHANGES.md
packages/devkit/package.json

Upgrade DOMPurify library to avoid deletion of some MathML tags by error.
Edit this MathML in e.g. CKEditor5:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mmultiscripts>
<msubsup>
<mi>c</mi>
<mi>h</mi>
<mi>h</mi>
</msubsup>
<mprescripts/>
<mi>h</mi>
<mi>h</mi>
</mmultiscripts>
</math>
```
Then check `mmultiscripts` tag is not be deleted
---
[#taskid 44328](https://wiris.kanbanize.com/ctrl_board/2/cards/44328/details/)

Upgrade DOMPurify library 

---

demos/vue/ckeditor5/index.html
packages/devkit/src/contentmanager.js
packages/devkit/src/core.src.js
packages/devkit/src/integrationmodel.js
packages/devkit/src/serviceprovider.js
packages/devkit/src/util.js
packages/viewer/src/app.ts
packages/viewer/src/properties.ts
packages/viewer/src/services.ts

Add customHeaders configuration on viewer.
To test this feature we will use the integration services in php deployed from plugins project.
**You will need to set html-integrations and plugins on branch KB-42329**
1. On `html-integrations/packages/viewer/properties.ts` replace the variable defaultValues (line 29) to:
```
const defaultValues: Config = {
editorServicesRoot: 'http://localhost:8081/plugin/3.50/tinymce6-demo/tinymce6/plugins/tiny_mce_wiris/integration/',
editorServicesExtension: '.php',
backendConfig: {
wirispluginperformance: 'true',
wiriseditormathmlattribute: 'data-mathml',
wiriscustomheaders: {},
},
dpi: 96,
element: 'body',
lang: 'en',
viewer: 'none',
zoom: 1,
}
```
2. Deploy php integration services with tinymce6 on plugins project.
3. On configuration.ini from the …

feat(viewer): add customheaders

---

CHANGES.md
demos/html/viewer/src/app.js
packages/viewer/src/mathml.ts
packages/viewer/src/services.ts

Render the formula that is not been cached in html-viewer.
- On the html-integration project build the viewer with nx build viewer
- Then start the viewer demo using with nx start html-viewer
- With `wirispluginperformance` checkbox `cheked` - On the content textarea update a non cached formula and press submit button
- With `wirispluginperformance` checkbox `uncheked` - On the content textarea update a non cached formula and press submit button
- Make sure there is not console error and the non-cached  formula must be rendered
---
[#taskid 44942](https://wiris.kanbanize.com/ctrl_board/2/cards/44942/details/)

Render the formula that is not been cached in html-viewer

---

demos/html/froala/package.json
packages/froala/wiris.src.js

Avoided froala cleanup functions on paste to conserve image attributes, improved legacy code.
(Chore): Change naming and more comments
The Froala Editor has a built-in cleanup process that removes unwanted HTML tags and attributes from the content. However, this cleanup process can cause issues when dealing with Wirisformulas. To prevent these issues, the code attaches a function to the 'paste.beforeCleanup' event of the Froala Editor. This event is triggered before the cleanup process starts. The regex looks for img tags that have a class attribute containing the word 'Wirisformula'. If a match is found, meaning a Wiris formula is detected, tells the Froala Editor to skip the cleanup process, thus preserving the Wiris formulas in their original state.
To reproduce
- Copy and paste a …

fix(froala): Editor bug with Wirisformulas paste behavior

---

.github/workflows/deploy-staging.yml

In this PR the github actions workflows are updated so the outputs are stored correctly, following these instructions https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Associated KB card: https://wiris.kanbanize.com/ctrl_board/2/cards/34039/details/

[KB-34039] Update how steps output are store in Github actions workflows.

---

packages/ckeditor5/src/integration.js
packages/devkit/src/contentmanager.js
packages/devkit/src/core.src.js
packages/devkit/src/integrationmodel.js
packages/devkit/src/modal.js
packages/devkit/src/popupmessage.js
packages/generic/wirisplugin-generic.src.js

` feat: update telemeter tracking to utilize promises. #KB-45700
`
This PR introduces a significant enhancement to our telemeter tracking functionality by transitioning all tracking actions to utilize promises. The motivation behind this change stems from a recent integration issue encountered with OnlyOffice.
1. Pull the `wiris/telemeter` repo.
2. Initiate the telemeter server by executing `cargo run` and ensure it's operational.
3. Navigate to `packages/devkit/src/Integrationmodel` on this branch.
4. Amend the code from `debug: false` to `debug: true`.
5. Execute `yarn && nx build generic && nx start html-generic` to build the generic editor.
6. Verify the connection of the generic editor to the telemeter server.
7. Interact with the generic editor by inserting formulas, closing, and …

 KB-45700: Update Telemeter Tracking to Utilize Promises

---

packages/ckeditor5/src/plugin.js

Refactor the functions for 'editor.setData' and 'editor.getData' in CKEditor 5 to accept additional arguments when calling the functions.
- Open a CKEditor5 demo.
- Check that there are no errors when calling 'editor.setData' and 'editor.getData' in CKEditor 5 (for example, when using source mode to edit).
---
[#taskid 43896](https://wiris.kanbanize.com/ctrl_board/2/cards/43896/details/)

Respect options passed to data controller on set

---

demos/html/viewer/src/app.js
packages/viewer/src/mathml.ts
packages/viewer/src/services.ts

To alllow Viewers to accept multiple MathML inputs and not halt execution of remaining formulas if one MathML format encounters an error.
1. Visit https://htmledit.squarefree.com/
2. Paste the following HTML, which contains a malformed mathml in the third equation:
```
<script src="https://integrations.wiris.kitchen/KB-43208/html/viewer/node_modules/@wiris/mathtype-viewer/dist/WIRISplugins.js?viewer=image"></script>
<h3>Hi! We're testing the Wiris viewer!</h3>
<p>LaTeX formula:
$$4 - 2 = 2$$
</p>
<p>MathML formula: <math xmlns="http://www.w3.org/1998/Math/MathML"><msqrt><mi>x</mi></msqrt></math></p>
<p>MathML formula:
<math>
<mn>2</mn>
<mo>+</mo>
mn>2</mn>
<mo=<s/mo>
<mn>4/mn
</math>
</p>
<p>LaTeX formula:
$$4 - 2 = 2$$
</p>
<p>MathML formula: <math …
```

Improve viewer behaviour on errors

---

.gitignore
packages/ckeditor4/plugin.src.js
packages/devkit/src/integrationmodel.js
packages/devkit/src/modal.js
packages/froala/wiris.src.js
packages/generic/wirisplugin-generic.src.js
packages/tinymce5/editor_plugin.src.js
packages/tinymce6/editor_plugin.src.js

This fix ensures that when the editor is closed all the MathType remainings (Modal, Events, Instances) are removed from the DOM.
The issue is fixed on #KB-44922 
The branch #KB-44922-test adds additional tools to test the fix.
Follow the next steps to reproduce.
* The next steps should reproduce under the next editors
* [Ckeditor4](https://integrations.wiris.kitchen/KB-44922-test/html/ckeditor4/)
* [Ckeditor5](https://integrations.wiris.kitchen/KB-44922-test/html/ckeditor5/)
* [Froala](https://integrations.wiris.kitchen/KB-44922-test/html/froala/)
* [TinyMCE4](https://integrations.wiris.kitchen/KB-44922-test/html/tinymce4/)
* [TinyMCE5](https://integrations.wiris.kitchen/KB-44922-test/html/tinymce5/)
* [Generic](https://integrations.wiris.kitchen/KB-44922-test/html/generic/)
1. Open the …

feat(demos): Destroy MathType when the editor is destroyed

---

packages/viewer/src/app.ts
packages/viewer/src/latex.ts
packages/viewer/src/properties.ts
packages/viewer/src/retro.ts
packages/viewer/tsconfig.json

- Add `strict: true` to the `tsconfig.json` file in the viewer package to enforce stricter typing. This will lead to more robust code and help catch potential bugs at compile time.
- Check the dev deploy [here](https://integrations.wiris.kitchen/fix/use-strict/html/viewer/), it should show the demo viewer and work as expected. 
- run: `nx build viewer && nx start html-viewer`, the code should compile and work as expected
- Setting strict to true has revealed a number of errors. Resolving some of these is innocuous, but addressing others involves assumptions that are not clear about what the code should do in certain cases. 
---
[#taskid X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/) (*Waiting for the card to be created*)

Add strict to ts-config

---

packages/viewer/src/properties.ts
packages/viewer/src/services.ts

This pull request improves the way we detect whether the user is making use of the integration services or, in its absence, wiris.net.
Prior to the development, we used a hard-coded string to identify the route where the integration services were hosted. That is a correct approach for the PHP ones, but in Java the user can change their location, making it impossible to detect since it did not match the Java hard-coded string.
The approach is to make a request to the current viewer URL, if we are not on PHP and receive an answer, it means that the client is using the Java integration services. Otherwise, it will default to wiris.net.
Case 1:
1. Using Plugins, deploy a Java demo with the instructions in the `build/docker` folder.
2. It should load properly the viewer from the location where …

Improve viewer integration services detection

---

packages/ckeditor5/src/plugin.js

Clicking in and out of the focus of the CKEditor causes unnecessary calls to render (showimage) when using our last version of MathType for CKEditor and the editor.getData() function.
[Check This ](https://codesandbox.io/p/devbox/uat-wiris-8-9-1-n3d55q)
Remove unnecessary calls to our image services
---
[#48217 X](https://wiris.kanbanize.com/ctrl_board/2/cards/48217/details/)

Clicking in and out of the focus of the CKEditor causes unnecessary calls to render

---

packages/viewer/src/app.ts
packages/viewer/src/latex.ts
packages/viewer/src/properties.ts
packages/viewer/src/retro.ts
packages/viewer/tsconfig.json

- Add `strict: true` to the `tsconfig.json` file in the viewer package to enforce stricter typing. This will lead to more robust code and help catch potential bugs at compile time.
- Check the dev deploy [here](https://integrations.wiris.kitchen/fix/use-strict/html/viewer/), it should show the demo viewer and work as expected. 
- run: `nx build viewer && nx start html-viewer`, the code should compile and work as expected
- Setting strict to true has revealed a number of errors. Resolving some of these is innocuous, but addressing others involves assumptions that are not clear about what the code should do in certain cases. 
---
[#taskid 47912](https://wiris.kanbanize.com/ctrl_board/2/cards/47912/details/) (*Waiting for the card to be created*)

fix: add strict to ts-config

---

packages/viewer/src/properties.ts
packages/viewer/src/services.ts

During the QA process, a console error was spotted. 
The error is due to a URL fetching where, when it fails, we can assume that the client will be using cloud and when it does not fail, we can assume that they will be using on-premises with Java.
This error is not possible to be removed, since it's handled by the browser, but we still want to let the user know that it won't impact negatively in any way. That's why this PR adds a warning for the specified check.
1. Open the viewer demo and validate that the warning appears.
---

fix(viewer): Fetch error on get configuration

---

packages/ckeditor4/plugin.src.js
packages/ckeditor5/src/integration.js

When multiple CK5 editors are present on a page, the selected editor cannot be properly focused, leading to an incorrect caret position after editing.
- **Related Kanbanize Card:** [Link to KB-48969](https://wiris.kanbanize.com/ctrl_board/2/cards/https://wiris.kanbanize.com/ctrl_board/2/cards/48969/details/)
- **Manual …

fix: focus on proper editor when have multiples

---

packages/devkit/src/util.js

When a formula with a superscript is added and then updated, it transforms to a subscript. The none tag, differentiates both and was deleted by dompurify.
- **Related Kanbanize Card:** [Link to KB-50069](https://wiris.kanbanize.com/ctrl_board/2/cards/50069/details/)
- **Related GitHub Issue:** Closes #1001 
> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
Add …

feat: Add "none" tag to supported MathML tags in Util class

---

packages/ckeditor5/package.json

⚠️  This PR is a prepared to work with new release of CKEditor5 in v43.0.0 (that will be released within a dew days). ⚠️ 
What has changed:
1. The global names for the `ckeditor5` and `ckeditor5-premium-features` packages in the UMD builds have been changed to `CKEDITOR` and `CKEDITOR_PREMIUM_FEATURES`, respectively.
2. Update the `exports` field in `package.json` to fix potential issues with loading CSS in older bundlers.
_If this PR solves a bug, include a short summary of the bug and the steps to reproduce it._
---
Closes #X (_Associated GitHub issue, if any_)
[#taskid X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/) (_Associated Kanbanize card, if any_)

Update `exports` in `package.json` and bump `ckeditor5` and `ckeditor5-dev-build-tools` packages.

---

packages/devkit/lang/strings.json

Added the missing Dutch translations keys:
- "manual"
- "insert_math"
- "accept"
When setting the language to 'nl', the following kind of warnings are logged to the console: `Unknown key insert_math for language nl in StringManager.`
---

Added missing Dutch translation keys;

---

demos/html/tinymce7/src/app.js
packages/tinymce7/README.md

TinyMCE does a filtering when there's an initial content to be inserted. This filter does not accept many of the MathML tags, that's why we use options such as `valid_elements` and `extended_valid_elements`. But this seems to not be enough because TinyMCE keeps removing the `<semantics>` tag. 
That is because they do not want to accept it in any case as it is a potential issue. The only solution is to disable their sanitization, in case we would like to keep the information on the handwriting formulas when they are set as initial content.
Check [this report to the TinyMCE GitHub](https://github.com/tinymce/tinymce/issues/10114) to find more information.
This PR will remove the sanitization for our development and staging demos and will add the information of this issue so that the client …

fix: TinyMCE7 sanitization

---

.github/workflows/staging-cleanup.yml

When the dismantle staging workflow fails, it does not perform a cleanup, so there could be branches on stable that are not present on the repository.
This PR introduces a new GitHub actions workflow to perform a staging cleanup for all the branches, leaving staging with only the branches present on the repository.
Run the workflow manually and validate that all the branches on the repository are the same you can find on staging.

Create staging cleanup repo

---

.github/workflows/dismantle-staging.yml

Dismantle staging workflow is not working when it finds branches with `/` brackets. 
This PR should fix the part of the workflow where it takes the branches on staging and removes them.
Once merged to master, we should validate it works by creating and removing a branch with `/`.

Fix dismantle staging workflow

---

packages/ckeditor5/src/index.js

When CKEditor5 updated their installation methods, we had to adapt to those. In the process, we lost the export of most classes.
- **Related Kanbanize Card:** [Link to KB-54691](https://wiris.kanbanize.com/ctrl_board/2/cards/54691/details/)
- **Related GitHub Issue:** Closes #1008
Validate that the `CKEditor5Integration`, `MathTypeCommand` and `ChemTypeCommand` are available to import when using MathType for CKEditor5.

fix: Export CK5 Wiris classes

---

packages/froala/wiris.src.js

The `contentChanged` event is triggered before a formula is inserted, making the content of the event to not have the recent changes on the Froala editor. 
We need to remove our own trigger to the event, as Froala already triggers it any time there's new content on the editor.
- **Related Kanbanize Card:** [Link to KB-55127](https://wiris.kanbanize.com/ctrl_board/2/cards/55127/details/)
* On the Froala demo, listen to the Froala `contentChanged` event.
* Insert a formula
* Validate that the content changed payload has the formula.

fix: Remove unnecessary contentChanged event

---

docs/contributing/README.md

Just added some info in contributing instructions.
Just read the changes.

docs: Update contributing instructions.

---

.github/workflows/deploy-staging.yml

When we manually trigger the publish workflow, it makes a commit and pushes it to master, but the push event will not trigger another workflow. This is a built-in GitHub restriction to prevent infinite workflow loops.
For that reason, we don't have staging up to date on the master branch, and is usually broken due to our release process. 
This PR adds a configuration to the staging workflow to force running it automatically when the publish one completes.
This will be validated in the next release. Check that the changes are well written

Make Staging workflow run when publish workflow completes

---

packages/devkit/src/contentmanager.js

Fix the issue where, in some cases, switching the text direction causes the editor to display in LTR mode, even though it is already in RTL mode.
This issue is exposed in the Tiny 7 plugin's demo, so the fix will solve the error in the plugin demo.
- **Related Kanbanize Card:** [Link to KB-56039](https://wiris.kanbanize.com/ctrl_board/2/cards/56039/details/)
[To reproduce error! Needs to be tested on another branch!]
1. Open html-integrations/demos/html/tinymce7/src/app.js
2. Change the language to Arabic by adding:
```
tinymce.init ({
mathTypeParameters: {
editorParameters: { language: 'ar' },
}
```
3. Force TinyMCE 7 to display in RTL mode by adding
```
tinymce.init ({
directionality: "rtl",
```
4. You’ll notice that when MathType opens, it appears in LTR mode, while it should be RTL
5. …

fix: prevent from change to wrong rtl state

---

demos/html/tinymce6/src/app.js
demos/html/tinymce7/package.json
demos/html/tinymce7/src/app.js
packages/tinymce6/README.md
packages/tinymce6/editor_plugin.src.js
packages/tinymce7/README.md
packages/tinymce7/editor_plugin.src.js

Update the demo and documentation to include the workaround for using extended_mathml_elements, extended_mathml_attributes.
These changes are made to ensure that MathML generated by MathType works correctly during both editing and viewing in TinyMCE 7, following it's 7.8 [release note](https://www.tiny.cloud/docs/tinymce/latest/7.8.0-release-notes/#new-extended_mathml_attributes-and-extended_mathml_elements-options).
- **Related Kanbanize Card:** [Link to KB-55936](https://wiris.kanbanize.com/ctrl_board/2/cards/55936/details/)
1. Launch tinycme 7' demo.
2. Try to add formulas with linebreak. For example: 
```<math style="font-family:'Times New Roman'" xmlns="http://www.w3.org/1998/Math/MathML"><mi>A</mi><mi>B</mi><mo>=</mo><mi>A</mi><mi>C</mi> …
```

fix: update demo with lastest tiny updates

---

packages/devkit/src/contentmanager.js
packages/devkit/src/focusprotection.js
packages/devkit/src/modal.js

Introduce a focus protection mechanism to prevent external scripts from interfering with the MathType modal dialog's focus management. This enhancement ensures that focus remains on the editor when the modal is active.
- **Related Kanbanize Card:** [Link to KB-56852](https://wiris.kanbanize.com/ctrl_board/2/cards/56852/details/)

Implement focus protection for MathType modal dialog

---

demos/html/froala/index.html
packages/froala/wiris.src.js

Disabling any of the buttons wirisEditor or wirisChemistry on the toolbarButtons list of Froala, will crash the init of Froala. This does not happen with both buttons added to the toolbarButtons option of the Froala editor.
The issue was solved by checking that the button existed before changing it's contents.
- **Related Kanbanize Card:** [Link to KB-57875](https://wiris.kanbanize.com/ctrl_board/2/cards/57875/details/)
1. Change Froala's language:
* Uncomment the line 7 on the `demos/html/froala/index.html` file.
*Uncomment the line 39 on the `demos/html/froala/src/app.js` file.
2. Remove `wirisEditor` or `wirisChemistry` from the toolbarButtons on the Froala's demo js-
3. Build and start the demo with `nx build froala` and `nx start html-froala`
4. The demo should start without the …

Fix froala buttons title translation
