CODE_OF_CONDUCT.md

I would remove the reporting part, for now, since it is not up to us, and add it in the future after we have made a decision about this section.

PLUGINS-1338

---

.eslintignore
demos/html5/froala3/test/e2e-editor-checkPageHeader.test.js
demos/react/ckeditor5/package.json
demos/react/froala3/package.json
demos/react/generic/package.json
demos/react/tinymce5/package.json
package-lock.json
package.json
packages/mathtype-ckeditor4/package-lock.json
packages/mathtype-html-integration-devkit/.eslintrc.json
packages/mathtype-html-integration-devkit/test/unit-accessibility-checkMathToAccessible.test.js

Test the command npm run lint in the root of the project and check that it lint all the project without errors

KB-4199: Solve the linting issue

---

demos/html5/ckeditor5/package-lock.json
packages/mathtype-ckeditor5/src/plugin.js

This pull request fixes issue #112, which throws an error when writing after a MathType formula in CKEditor 5.
1. Open a CKEditor 5 HTML5 demo
2. Write some text, followed by a space
3. Add a MathType equation, followed by a space
4. Type some text
Expected: the text is inserted, no error is thrown.
Actual: the text appears to be inserted, but an error is thrown, and the CKEditor engine doesn't actually process the inserted text.
For more details see #112.

Fix CKEditor 5 "modelWriter.createElement() is not a function" error

---

CONTRIBUTING.md
README.md
demos/README.md

Check that all the README files have the correct support e-mail: support@wiris.com

Fix the support contact e-mail

---

demos/html5/generic/package-lock.json
demos/html5/generic/package.json

This pull request contains:
- Update dependencies to avoid vulnerabilities.
- Move code validation to root level.

Bump html5/generic demo version to 1.0.1

---

README.md
demos/README.md
demos/angular/ckeditor5/package.json
demos/angular/froala3/package.json
demos/angular/generic/package.json
demos/angular/tinymce5/package.json
demos/html5/ckeditor4/package.json
demos/html5/ckeditor5/package.json
demos/html5/froala2/package.json
demos/html5/froala3/package.json
demos/html5/generic/package.json
demos/html5/tinymce4/package.json
demos/html5/tinymce5/package.json
demos/react/ckeditor5/package.json
demos/react/froala3/package.json
demos/react/generic/package.json
demos/react/tinymce5/package.json
package.json
packages/mathtype-ckeditor4/package.json
packages/mathtype-froala/package.json
packages/mathtype-froala3/package.json
packages/mathtype-generic/package.json
packages/mathtype-html-integration-devkit/package.json
packages/mathtype-tinymce4/package.json
packages/mathtype-tinymce5/package.json

There have been issues and inconsistencies in the different Node.js projects inside the html-integrations repository (root, package, and demos).
Some of the identified issues are:
- npm scripts that do not run or finish properly.
- Redundant, missing, or misplaced dependencies.
To mitigate these issues, the following actions will be taken:
- Ensure that all npm commands work properly and follow the same conventions.
- Improve the commands where possible.
- Move correctly the dependencies between packages.
When reviewing, pay special attention to the documentation (the modified READMEs).
#taskid 11601

Fix and validate the Node.js project configuration

---

.github/dependabot.yml

Add comments to the dependabot.yaml file to make it moreunderstandable

Document dependabot.yaml file

---

docs/adr/003--use-shx-wrapper-for-shell-commands.md

When writing custom scripts in the node project that perform common tasks like file manipulation (deleting, moving ...) we want to ensure cross-platform compatibility while keeping a simple syntax and reducing vulnerability issues. 
We decided to use shx package as a wrapper around ShellJS Unix commands in all scripts of the project.

KB-11601: Add an ADR document for the shell command wrapper of choice 

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml

This PR adds templates for issues (bug reports only) and pull requests.

Issue and Pull Request Templates

---

CHANGES.md
README.md

From now on, in order to reduce the effort required to maintain the release notes of our projects, all notable changes to this project will be documented in the CHANGES.md file.
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
We will keep an Unreleased section at the top of this document to track upcoming changes. 
Therefore, everytime any team-mate creates a Pull Request with new changes, this file needs to be update accordingly with a new entry on the Unreleased section.
This serves two purposes:
- People can see what changes they might expect in upcoming releases
- At release time, you can move the Unreleased section changes into a new release version section.
Also aded the full list of published packages on npm with its version numbers.
| Name …

KB-12610: Add a changelog list to the project

---

.eslintrc.js
cypress/fixtures/formulas.json
cypress/support/command.d.ts
cypress/support/commands.js
cypress/support/index.js
cypress/support/validations.d.ts
cypress/tests/sandbox/mathtype_button.spec.js
cypress/tests/smoke/formula.Create.a.formula.from.scratch.(INT-STD-014).js

This PR contains the code part of task [KB-13068](https://wiris.kanbanize.com/ctrl_board/2/cards/13068/details/), as designed by @carla-at-wiris and me.
- Design a starter API of commands and validations for Cypress, including type definitions.
- Add a common array of fixtures, based on the tests proposed by QA.

MathType Integrations Test plan: Design the solution

---

packages/mathtype-html-integration-devkit/lang/strings.json

Update strings.json (Hebrew strings updates)

---

demos/html5/ckeditor4/package.json
demos/html5/ckeditor5/package.json
demos/html5/froala2/package.json
demos/html5/froala3/package.json
demos/html5/tinymce4/package-lock.json
demos/html5/tinymce4/package.json
demos/html5/tinymce5/package.json
package-lock.json
package.json
packages/mathtype-ckeditor5/package.json
packages/mathtype-html-integration-devkit/package.json

Remove Jest dependency from the project since it's not used anymore
#taskid [14421](https://wiris.kanbanize.com/ctrl_board/2/cards/14421/details/)

KB:14421: Remove Jest dependency from the project since it's not used anymore

---

CHANGES.md
packages/mathtype-froala/README.md
packages/mathtype-froala3/README.md
packages/mathtype-tinymce4/README.md

Add deprecation warning message on `mathtype-froala`, `mathtype-froala3` and `mathtype-tinymce3` READMEs

docs: add deprecation warning message on froala and tinymce4 package

---

.gitignore
terraform/.terraform.lock.hcl
terraform/aws.tf
terraform/backend.staging.conf
terraform/integrations.staging.tfvars
terraform/variables.tf

*What does this PR fix or add?*
Add IAC.
*If this PR solves a bug, include a short summary of the bug and the steps to reproduce it.*
N/A
---
Closes #X (*Associated GitHub issue, if any*)
N/A
[#taskid X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/) (*Associated Kanbanize card, if any*)
https://wiris.kanbanize.com/ctrl_board/15/cards/29381/details/

feat: add terraform code

---

demos/angular/froala/README.md
demos/react/froala/README.md
packages/froala/README.md
packages/froala/wiris.src.js

Reverts wiris/html-integrations#647

Revert "fix: Autofocus not working"

---

demos/html/generic/index.html
packages/res/demos/index.html

Add xmlns attribute to default formulas
---
[#taskid 31737](https://wiris.kanbanize.com/ctrl_board/2/cards/31737/details/)

fix: add xmlns attribute to default formulas

---

packages/viewer/package.json
packages/viewer/src/app.ts
packages/viewer/src/properties.ts
packages/viewer/src/services.ts

* Improve image generation.
* Separate functions in different files.
* Create common functions.
* Make the functions independent of each other.
1. Start the viewer demo to see the changes.
---
[#taskid 32160](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/) (*Associated Kanbanize card, if any*)

feat: Add features to the viewer proof of concept

---

packages/viewer/index.html
packages/viewer/package.json
packages/viewer/src/app.ts
packages/viewer/src/properties.ts
packages/viewer/src/services.ts
packages/viewer/webpack.config.js

Includes rendering LaTeX formulas on the viewer package

feat: viewer latex render

---

packages/ckeditor5/src/integration.js

When the user edits a LaTeX formula placed in the same line as a formula, when trying to edit the LaTeX formula with the Insert button in the MT/CT Editor does not work.
The CKEditor5 has a `writer` class with its own methods, which is the one in charge of inserting, modifying, and many other functionalities on the text editor. This PR solved the issue using the `writer` class functionalities
1. Install dependencies with `yarn` and build the CKEditor5 with `nx build ckeditor5`.
2. Open the demo with `nx start html-ckeditor5`.
3. Write a LaTeX formula next to the quadratic formula, for example, `$$\sqrt{x}$$`.
4. Place the caret inside the previously inserted formula.
5. Click on the MT/CT icon to open the MT/CT Editor.
6. Edit the LaTeX formula in the MT/CT Editor.
7. Click on Insert in …

Fix LaTeX not working next to formula

---

packages/tinymce6/editor_plugin.src.js

This is a bug that stops the TinyMCE 6 demo from taking the MathType parameters (e.g. color, toolbar, etc.)
It happens because the TinyMCE 6 plugin code is not adapted to the TinyMCE 6 EditorOptions API.
1. Make sure that you are on the `KB-32247` branch on both `html-integrations` and `plugins`.
2. Start the `plugins` TinyMCE 6 demo for any technology.
3. Open the demo.
4. Check the "Advanced options" checkbox at the bottom.
5. Click on "Set" with the default parameters.
Expected outcome: the editor changes its values.
Actual outcome: the editor doesn't react to the changes.
---
[#taskid 32247](https://wiris.kanbanize.com/ctrl_board/2/cards/32247/details/)

"Advanced Options" not working on the TinyMCE demo in order to modify the toolbar

---

.github/workflows/publish.yml
packages/viewer/package.json

Add `prepack` script to the viewer in order to build the viewer package when using `npm run publish`
---
[#taskid 34549](https://wiris.kanbanize.com/ctrl_board/2/cards/34549/details/)

feat: add prepack script to viewer

---

.github/workflows/publish.yml
packages/devkit/src/parser.js
packages/viewer/README.md
packages/viewer/babel.config.js
packages/viewer/docs/spec.md
packages/viewer/index.html
packages/viewer/package.json
packages/viewer/src/app.ts
packages/viewer/src/latex.ts
packages/viewer/src/mathml.ts
packages/viewer/src/properties.ts
packages/viewer/src/services.ts
packages/viewer/tsconfig.json
packages/viewer/typings/module-name.d.ts
packages/viewer/webpack.config.js

This PR adds the main set of features of the new viewer.
To check that everything is correct, compare to the specification (see [card](https://wiris.kanbanize.com/ctrl_board/2/cards/34546/details/)) and test the demo included in the package itself (`yarn serve` in `packages/viewer`).
Please don't hesitate to ask or comment on any possible improvement or missing feature.
---
[#taskid 34546](https://wiris.kanbanize.com/ctrl_board/2/cards/34546/details/)

Develop the main set of features of the viewer

---

.gitignore
demos/angular/ckeditor5/src/app/app.component.ts
demos/angular/froala/src/app/app.component.ts
demos/angular/generic/src/app/app.component.ts
demos/angular/tinymce5/src/app/app.component.ts
demos/html/ckeditor4/src/app.js
demos/html/ckeditor5/src/app.js
demos/html/froala/package.json
demos/html/froala/src/app.js
demos/html/generic/index.html
demos/html/generic/src/app.js
demos/html/tinymce5/src/app.js
demos/html/tinymce6/src/app.js
demos/react/ckeditor5/src/index.js
demos/react/froala/src/index.js
demos/react/generic/src/index.js
demos/react/tinymce5/src/index.js
package.json
packages/res/demos/common.js
packages/res/demos/design.css
packages/res/demos/index.html
packages/res/git-data.mjs

This PR adds the information of the GitHub branch and commit to the demo pages.
1. Go to all staging demos.
2. Validate that they all have the new information matching this current branch and its latest commit.
---
[#taskid 34114](https://wiris.kanbanize.com/ctrl_board/2/cards/34114/details/)

Add GitHub information to the demo

---

packages/viewer/src/services.ts

Reverts wiris/html-integrations#872

Revert "fix(viewer): hash all parameters before sending get showimage request"

---

demos/html/viewer/index.html
demos/html/viewer/src/static/style.css
packages/viewer/src/app.ts
packages/viewer/src/retro.ts

This PR is a refactor for the viewer demo.
1. Build the viewer demo with `nx build viewer`
2. Start the viewer demo with `nx start html-viewer`
Test to change some configuration.
---
[#taskid 40530](https://wiris.kanbanize.com/ctrl_board/2/cards/40530/details/)

feat: improve viewer

---

CHANGES.md
packages/devkit/src/util.js

Add DOMPurify exceptions

---

.vscode/settings.json
docs/development/demos/README.md

[Duplicate](https://github.com/wiris/html-integrations/pull/928)

Add known issues

---

.github/workflows/deploy-staging.yml
CHANGES.md
demos/html/viewer/index.html
demos/html/viewer/package.json
demos/html/viewer/project.json
demos/html/viewer/src/app.js
demos/html/viewer/src/static/style.css

Add new 'Commit hash' field to html-viewer demo.
1. Open html-viewer demo
2. Check that commit hash exists
---
[#taskid 44411](https://wiris.kanbanize.com/ctrl_board/2/cards/44411/details/)

Add commit hash

---

.github/CODEOWNERS

fix: updated codeowners

---

.vscode/settings.json

feat: Update ESLint configuration to fix all errors on save

---

packages/ckeditor5/src/plugin.js

- **Related Kanbanize Card:** [Link to KB-50469](https://wiris.kanbanize.com/ctrl_board/2/cards/50469/details/)

feat: performance improvement

---

packages/ckeditor5/src/plugin.js

- **Related Kanbanize Card:** [Link to KB-X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/)
- **Related GitHub Issue:** Closes #X (_Associated GitHub issue, if any_)

fix(ck5): filter no wiris image on setdata

---

docs/demos/README.md
docs/development/cicd/README.md
packages/ckeditor4/package.json
packages/ckeditor5/dist/browser/index.js
packages/ckeditor5/dist/browser/index.umd.js
packages/ckeditor5/dist/index.js
packages/ckeditor5/package.json
packages/devkit/package.json
packages/froala/package.json
packages/generic/package.json
packages/tinymce5/package.json
packages/tinymce6/package.json
packages/wordpress/package.json

Removes stable mentions to align with the new GitHub policies.

Remove stable mentions

---

.github/CODEOWNERS

- **Related Kanbanize Card:** [Link to KB-X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/)
- **Related GitHub Issue:** Closes #X (_Associated GitHub issue, if any_)

feat: Add nicolas to codeowners

---

demos/html/ckeditor5/src/app.js
demos/vue/ckeditor5/src/App.vue

With the new release version of CKEditor 5, it is required to include the licenseKey field when instantiating the editor. Otherwise, our demo won't launch.
- **Related Kanbanize Card:** [Link to KB-52783](https://wiris.kanbanize.com/ctrl_board/2/cards/52783/details/)
- **Manual tests:** Try to launch CKEditor 5 demo.

Add licenseKey for CKEditor5's demo setup

---

.github/workflows/jsdoc.yml

Just upgraded an obsolete action version.

chore: Update action version.

---

.github/workflows/deploy-staging.yml
demos/html/tinymce7/babel.config.js
demos/html/tinymce7/index.html
demos/html/tinymce7/package.json
demos/html/tinymce7/project.json
demos/html/tinymce7/src/app.js
demos/html/tinymce7/src/static/style.css
demos/html/tinymce7/webpack.config.js
packages/tinymce7/README.md
scripts/services/paths.json
staging/branch/html/index.html
staging/branch/index.html

Given that we have previously created a TinyMCE plugin to support the version 7, this PR created a demo for it.
- **Related Kanbanize Card:** [Link to KB-53359](https://wiris.kanbanize.com/ctrl_board/2/cards/53359/details/)
* Try out the demo and validate that it is working as expected, with no new bugs or new console errors showing up.
* Validate that the staging demo is also working properly for TinyMCE7.

Create TinyMCE 7 demo

---

CHANGES.md
packages/ckeditor4/package.json
packages/ckeditor5/dist/browser/index.js
packages/ckeditor5/dist/browser/index.umd.js
packages/ckeditor5/dist/index.js
packages/ckeditor5/package.json
packages/froala/package.json
packages/generic/package.json
packages/tinymce5/package.json
packages/tinymce6/package.json
packages/tinymce7/package.json
packages/viewer/package.json

Chore changes for the release
- **Related Kanbanize Card:** [Link to KB-X](https://wiris.kanbanize.com/ctrl_board/2/cards/X/details/)
- **Related GitHub Issue:** Closes #X (_Associated GitHub issue, if any_)

chore: Update Changes.md and devkit dependencies

---

.github/workflows/dismantle-staging.yml
.github/workflows/staging-cleanup.yml
demos/html/tinymce7/package.json
demos/html/tinymce7/src/app.js
packages/tinymce7/README.md

This PR updates the TinyMCE version to `7.7.0`, as well as the configuration parameters.
* Removes the parameter that prevent the DOMPurify to clean our HTML.
* Adds the parameter `allow_mathml_annotation_encodings` to prevent DOMPurify from removing `semantics` and `annotations` tags.
* Update NPM documentation
With this change, the HTML is still validated by the DOMPurify library and our MathML keeps our information.
- **Related Kanbanize Card:** [Link to KB-54591](https://wiris.kanbanize.com/ctrl_board/2/cards/54591/details/)
Build and start the TinyMCE 7 demo with the following commands:
```bash
nx build tinymce7
nx start html-tinymce7
```
Validate that the original formulas in the demo contain the `semantics` and `annotations` tags. 
Validate as well that the handwritten formulas, …

fix: Update TinyMCE 7 dependency

---

packages/tinymce7/README.md

Delete deprecated information.

doc: delete known issue section
